const {chromium}=require('playwright'),fs=require('fs'),assert=require('assert/strict');
const base=process.env.P122B_BASE||'http://127.0.0.1:8791',out=process.env.P122B_OUT||'/workspace/p12-2b-storage/EVIDENCE/EXTENDED';fs.mkdirSync(out,{recursive:true});let browser;
const result={checks:[],errors:[],result:'RUNNING',syntheticOnly:true},x={id:'EXT_OLD',subject:'Tin học 6',grade:6,week:5,period:9,title:'TEST ONLY',screens:[{content:'TASK',steps:['FIRST','FUTURE'],teacherNote:'PRIVATE'}]};
const pass=(name,data={})=>{result.checks.push({name,result:'PASS',data});console.log(name)};
async function fresh(){const c=await browser.newContext();c.on('page',p=>p.on('pageerror',e=>result.errors.push(e.message)));const t=await c.newPage();await t.goto(base+'/WEB_LIVE/teacher.html');await t.evaluate(()=>WebLiveSubjectStorage.ready);return {c,t};}
const list=t=>t.evaluate(()=>WebLiveSubjectStorage.listLessons());
async function seed(t,value=x){await t.evaluate(value=>{localStorage.setItem('lesson:'+value.id,JSON.stringify(value));localStorage.setItem('webLiveLibrary',JSON.stringify([{id:value.id,title:value.title}]));localStorage.setItem('foreign:private','KEEP');},value);await t.evaluate(()=>WebLiveSubjectStorage.refresh());}
async function totals(t){return t.evaluate(async()=>{const db=await new Promise(r=>{const q=indexedDB.open('WEB_LIVE_DB');q.onsuccess=()=>r(q.result)});const v=await new Promise(r=>{const tx=db.transaction(['lessons','assets','pending']),v={};for(const n of tx.objectStoreNames){const q=tx.objectStore(n).count();q.onsuccess=()=>v[n]=q.result;}tx.oncomplete=()=>r(v)});db.close();return v;});}
(async()=>{
 browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});let {c,t}=await fresh();await seed(t);const raw=await t.evaluate(()=>localStorage.getItem('lesson:EXT_OLD'));await t.evaluate(()=>WebLiveSubjectStorage.migrateLegacyLesson('EXT_OLD'));assert.deepEqual(await t.evaluate(()=>WebLiveSubjectStorage.readLesson('EXT_OLD')),x);assert.equal(await t.evaluate(()=>localStorage.getItem('lesson:EXT_OLD')),raw);pass('LEGACY_WITHOUT_SOURCEKEY_LOSSLESS_MIGRATION');
 await t.evaluate(async()=>{const old=await WebLiveSubjectStorage.readLesson('EXT_OLD');await WebLiveSubjectStorage.saveLesson({...old,grade:8},'json:new-metadata-revision');});assert.equal((await totals(t)).lessons,1);assert.equal((await t.evaluate(()=>WebLiveSubjectStorage.readLesson('EXT_OLD'))).grade,8);assert.equal(await t.evaluate(()=>localStorage.getItem('lesson:EXT_OLD')),raw);pass('SAME_ID_METADATA_UPDATE_NO_DUPLICATE_OLD_RETAINED');
 await t.evaluate(()=>{const g=IDBObjectStore.prototype.get;window.__g=g;IDBObjectStore.prototype.get=function(k){if(this.name==='lessons')throw Error('Read unavailable');return g.call(this,k)};});await assert.rejects(t.evaluate(()=>WebLiveSubjectStorage.readLesson('EXT_OLD')));await t.evaluate(()=>{IDBObjectStore.prototype.get=window.__g;});pass('UPDATED_LESSON_REJECTS_STALE_LEGACY_FALLBACK');await c.close();

 ({c,t}=await fresh());const uri=await t.evaluate(()=>{const c=document.createElement('canvas');c.width=c.height=64;c.getContext('2d').fillRect(0,0,64,64);return c.toDataURL()});await t.evaluate(async({x,uri})=>{for(const id of ['SHARED_A','SHARED_B'])await WebLiveSubjectStorage.saveLesson({...x,id,screens:[{imageData:uri,geometryImageData:uri,content:'TEST'}]});},{x,uri});assert.equal((await totals(t)).assets,1);await t.evaluate(()=>WebLiveSubjectStorage.deleteLesson('SHARED_A'));assert.equal((await totals(t)).assets,1);assert.equal((await t.evaluate(()=>WebLiveSubjectStorage.readLesson('SHARED_B'))).screens[0].imageData,uri);await t.evaluate(()=>WebLiveSubjectStorage.deleteLesson('SHARED_B'));assert.equal((await totals(t)).assets,0);pass('SHARED_ASSET_DELETE_OWNERSHIP_SAFE_AND_FINAL_ZERO_REFERENCE_DELETE');await c.close();

 ({c,t}=await fresh());await seed(t);await t.evaluate(()=>{const p=IDBObjectStore.prototype.put;window.__p=p;IDBObjectStore.prototype.put=function(...args){if(this.name==='lessons')throw new DOMException('Commit write fail','QuotaExceededError');return p.apply(this,args);};});await assert.rejects(t.evaluate(()=>WebLiveSubjectStorage.migrateLegacyLesson('EXT_OLD')));assert.equal((await totals(t)).lessons,0);assert.equal((await t.evaluate(()=>WebLiveSubjectStorage.readJournal('EXT_OLD'))).COMMITTED,false);assert.equal(await t.evaluate(()=>localStorage.getItem('lesson:EXT_OLD')),JSON.stringify(x));await t.evaluate(()=>{IDBObjectStore.prototype.put=window.__p;});pass('COMMIT_WRITE_FAILURE_ABORT_NO_FALSE_COMMIT_NO_PAGEERROR');
 await t.evaluate(()=>{const g=IDBObjectStore.prototype.get;window.__g=g;IDBObjectStore.prototype.get=function(...args){const q=g.apply(this,args);if(this.name==='pending')q.addEventListener('success',()=>{q.result.body.screens[0].content='CORRUPT_READBACK';});return q;};});await assert.rejects(t.evaluate(()=>WebLiveSubjectStorage.migrateLegacyLesson('EXT_OLD')));assert.equal((await totals(t)).lessons,0);await t.evaluate(()=>{IDBObjectStore.prototype.get=window.__g;});pass('READBACK_HASH_MISMATCH_PREVENTS_COMMIT');await t.evaluate(()=>WebLiveSubjectStorage.migrateLegacyLesson('EXT_OLD'));assert.equal((await totals(t)).pending,0);pass('FAILURE_RETRY_IDEMPOTENT_TARGET_REWRITE');await c.close();

 ({c,t}=await fresh());await seed(t);await t.evaluate(()=>{localStorage.setItem('lesson:CORRUPT_OLD','{"id":"CORRUPT_OLD","screens":[]}');});await t.evaluate(()=>WebLiveSubjectStorage.refresh());assert(await t.locator('#library').textContent());await assert.rejects(t.evaluate(()=>WebLiveSubjectStorage.migrateLegacyStorage()));assert.equal(await t.evaluate(()=>WebLiveSubjectStorage.getStorageHealth().status),'FAILED');assert.equal(await t.evaluate(()=>localStorage.getItem('lesson:CORRUPT_OLD')),'{"id":"CORRUPT_OLD","screens":[]}');assert.equal(await t.evaluate(()=>localStorage.getItem('foreign:private')),'KEEP');pass('CORRUPT_SOURCE_NO_FALSE_LIBRARY_MIGRATION_SUCCESS_FOREIGN_PRESERVED');await c.close();
 ({c,t}=await fresh());await seed(t);await t.evaluate(()=>{localStorage.setItem('webLiveLibrary','INVALID JSON');});await t.evaluate(()=>WebLiveSubjectStorage.refresh());assert((await list(t)).some(row=>row.id==='EXT_OLD'));await assert.rejects(t.evaluate(()=>WebLiveSubjectStorage.migrateLegacyStorage()));assert.equal(await t.evaluate(()=>localStorage.getItem('webLiveLibrary')),'INVALID JSON');assert.equal((await totals(t)).lessons,0);pass('CORRUPT_LIBRARY_INDEX_BLOCKS_MIGRATION_NO_SILENT_OMISSION');await c.close();

 ({c,t}=await fresh());await seed(t);await t.evaluate(async()=>start(await WebLiveSubjectStorage.readLesson('EXT_OLD')));await t.evaluate(()=>showImporter());await t.locator('#lessonSubject').selectOption('informatics');const newer={...x,id:'CANCEL_NEW'};await t.locator('#jsonfile').setInputFiles({name:'TEST_ONLY.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(newer))});await t.waitForFunction(()=>!document.getElementById('subjectLoadBtn').disabled);await t.evaluate(()=>{const native=IDBDatabase.prototype.transaction;IDBDatabase.prototype.transaction=function(...args){const tx=native.apply(this,args);if(args[1]==='readonly'&&Array.from(tx.objectStoreNames).includes('pending'))Object.defineProperty(tx,'oncomplete',{set(fn){tx.addEventListener('complete',event=>{window.__release=()=>fn.call(tx,event);window.__held=true;});},get(){return null;}});return tx;};});await t.locator('#subjectLoadBtn').click();await t.waitForFunction(()=>window.__held);await t.locator('#lessonSubject').selectOption('algebra');await t.evaluate(()=>window.__release());await t.waitForFunction(()=>document.getElementById('subjectStorageWarning').textContent.includes('lựa chọn đã thay đổi'));assert.equal(await t.evaluate(()=>currentLessonId),'EXT_OLD');assert.equal(await t.evaluate(()=>localStorage.getItem('lesson:CANCEL_NEW')),null);pass('ASYNC_SELECTION_CHANGE_PRESERVES_CURRENT_NO_LATE_START');await c.close();

 ({c,t}=await fresh());const peer=await c.newPage();await peer.goto(base+'/WEB_LIVE/teacher.html');await peer.evaluate(()=>WebLiveSubjectStorage.ready);await t.evaluate(x=>WebLiveSubjectStorage.saveLesson({...x,id:'PEER_NEW'}),x);await peer.waitForFunction(()=>WebLiveSubjectStorage.listLessons().some(row=>row.id==='PEER_NEW'));await peer.evaluate(()=>WebLiveSubjectStorage.deleteLesson('PEER_NEW'));await t.waitForFunction(()=>!WebLiveSubjectStorage.listLessons().some(row=>row.id==='PEER_NEW'));pass('CROSS_TAB_LIBRARY_METADATA_REFRESH_SAVE_DELETE');await t.evaluate(x=>WebLiveSubjectStorage.saveLesson({...x,id:'MISMATCH_SAVED'}),x);await t.evaluate(()=>showImporter());await t.locator('#lessonSubject').selectOption('algebra');await t.evaluate(()=>openSaved('MISMATCH_SAVED'));await t.waitForFunction(()=>document.getElementById('error').textContent.includes('không khớp'));assert.equal(await t.locator('#lessonSubject').inputValue(),'algebra');assert(await t.locator('#subjectLoadBtn').isDisabled());pass('SAVED_REFERENCE_SUBJECT_MISMATCH_BLOCK_PRESERVED');await c.close();

 c=await browser.newContext();c.on('page',p=>p.on('pageerror',e=>result.errors.push(e.message)));t=await c.newPage();await t.goto(base+'/');await t.evaluate(async()=>{const d=await new Promise(r=>{const q=indexedDB.open('WEB_LIVE_DB',2);q.onupgradeneeded=()=>q.result.createObjectStore('unknown');q.onsuccess=()=>r(q.result);});await new Promise(r=>{const tx=d.transaction('unknown','readwrite');tx.objectStore('unknown').put('KEEP','foreign');tx.oncomplete=r;});d.close();});await t.goto(base+'/WEB_LIVE/teacher.html');await t.evaluate(()=>WebLiveSubjectStorage.ready);assert.equal(await t.evaluate(()=>WebLiveSubjectStorage.getStorageHealth().status),'DB_UNAVAILABLE');const oldSchema=await t.evaluate(async()=>{const d=await new Promise(r=>{const q=indexedDB.open('WEB_LIVE_DB',2);q.onsuccess=()=>r(q.result);});const value=await new Promise(r=>{const q=d.transaction('unknown').objectStore('unknown').get('foreign');q.onsuccess=()=>r(q.result);});d.close();return value;});assert.equal(oldSchema,'KEEP');pass('UNSUPPORTED_SCHEMA_NO_DOWNGRADE_OR_DELETE_DATABASE');await c.close();
 assert.deepEqual(result.errors,[]);result.result='PASS';fs.writeFileSync(out+'/EXTENDED_RESULTS.json',JSON.stringify(result,null,2)+'\n');await browser.close();
})().catch(async e=>{result.result='FAIL';result.error={message:e.message,stack:e.stack};fs.writeFileSync(out+'/EXTENDED_RESULTS.json',JSON.stringify(result,null,2)+'\n');await browser?.close();console.error(e);process.exitCode=1;});
