import os,json,pathlib,subprocess,concurrent.futures,hashlib,time
p=pathlib.Path('/workspace/p12-2b-storage');r=p/'working/WEB_LIVE_STORAGE_P12_2B_WORKING_COPY';reg=p/'EVIDENCE/REGRESSION';out=p/'EVIDENCE/FINAL_RUN';out.mkdir(parents=True,exist_ok=True)
env=dict(os.environ,NODE_PATH='/opt/codex/runtimes/codex-primary-runtime/dependencies/node/node_modules');root=str(r);base='http://127.0.0.1:8791'
jobs=[('P121_TARGETED','/workspace/p12-1-legacy-subject/targeted.cjs',{'P121_ROOT':root,'P121_BASE':base,'P121_OUT':str(p/'EVIDENCE/TARGETED')}),('STORAGE',str(p/'storage-tests.cjs'),{}),('EXTENDED',str(p/'extended-tests.cjs'),{}),('SCALE',str(p/'scale-tests.cjs'),{}),('LIBRARY',str(reg/'library-tests.cjs'),{'P12_ROOT':root,'P12_BASE':base,'P12_LIBRARY_OUT':str(p/'EVIDENCE/LIBRARY')}),('GEOMETRY',str(reg/'geometry-runtime.cjs'),{}),('ALGEBRA',str(reg/'targeted-algebra.cjs'),{'WEB_LIVE_ALGEBRA_ROOT':root,'WEB_LIVE_ALGEBRA_BASE':base}),('INFORMATICS',str(reg/'targeted-informatics.cjs'),{'WEB_LIVE_INFORMATICS_ROOT':root,'WEB_LIVE_INFORMATICS_BASE':base}),('LEGACY_MULTI_ENGINE',str(reg/'engines.cjs'),{'WEB_LIVE_TEST_ROOT':root,'WEB_LIVE_BROWSER_BASE':base,'PHASE2_EVIDENCE':str(reg/'MULTI_ENGINE')})]
before={str(f.relative_to(r/'WEB_LIVE')):hashlib.sha256(f.read_bytes()).hexdigest() for f in (r/'WEB_LIVE').rglob('*') if f.is_file()};(out/'TESTED_RUNTIME_MANIFEST.json').write_text(json.dumps(before,indent=2))
def run(job):
 name,script,extra=job;t=time.monotonic();v=subprocess.run(['node',script],env=env|extra,capture_output=True,text=True);(out/(name+'.log')).write_text(v.stdout+v.stderr);return {'suite':name,'exitCode':v.returncode,'seconds':round(time.monotonic()-t,2),'result':'PASS' if v.returncode==0 else 'FAIL'}
results=[]
with concurrent.futures.ThreadPoolExecutor(max_workers=3) as pool:
 for x in pool.map(run,jobs):results.append(x);print(json.dumps(x),flush=True)
after={str(f.relative_to(r/'WEB_LIVE')):hashlib.sha256(f.read_bytes()).hexdigest() for f in (r/'WEB_LIVE').rglob('*') if f.is_file()};result={'result':'PASS' if all(x['exitCode']==0 for x in results) and before==after else 'FAIL','testedRuntimeUnchanged':before==after,'suites':results,'windows':'UNRUN','physicalTV':'UNRUN','classroom':'UNRUN'};(out/'FINAL_RUN_RESULTS.json').write_text(json.dumps(result,indent=2));print(json.dumps(result),flush=True);raise SystemExit(0 if result['result']=='PASS' else 1)
