const {chromium}=require('playwright'),fs=require('fs'),assert=require('assert/strict'),path=require('path');
const base=process.env.P122B_BASE||'http://127.0.0.1:8791',root=process.env.P122B_ROOT||'/workspace/p12-2b-storage/working/WEB_LIVE_STORAGE_P12_2B_WORKING_COPY',out=process.env.P122B_OUT||'/workspace/p12-2b-storage/EVIDENCE/STORAGE';fs.mkdirSync(out,{recursive:true});
const result={mode:'REAL_CHROMIUM_INDEXEDDB_WITH_DISPOSABLE_ORIGINS',checks:[],errors:[],windows:'UNRUN',cleanup:'NOT_RUN_BY_DESIGN'},tiny={id:'OLD_SMALL',subject:'Tin học 6',grade:6,week:5,period:9,title:'TEST ONLY old small',_runtimeSourceKey:'json:oldsmall',screens:[{type:'QUICK_CHECK',content:'Chọn một.',options:['A','B'],answer:'A'},{type:'PRACTICE',content:'Nhiệm vụ',steps:['STEP1','FUTURE_STEP2'],teacherNote:'PRIVATE_ONLY'}]};let browser;
const pass=(name,detail={})=>{result.checks.push({name,result:'PASS',detail});console.log(name)};
async function fresh(hook){const c=await browser.newContext({viewport:{width:1366,height:768}});c.on('page',p=>p.on('pageerror',e=>result.errors.push(e.message)));if(hook)await c.addInitScript(hook);const t=await c.newPage();await t.goto(base+'/WEB_LIVE/teacher.html');await t.evaluate(()=>WebLiveSubjectStorage.ready);return {c,t};}
async function counts(t){return t.evaluate(async()=>{const d=await new Promise((r,j)=>{const x=indexedDB.open('WEB_LIVE_DB');x.onsuccess=()=>r(x.result);x.onerror=()=>j(x.error)});const data=await new Promise((r,j)=>{const tx=d.transaction(['lessons','assets','pending','journal']),s={};for(const n of tx.objectStoreNames){const x=tx.objectStore(n).getAll();x.onsuccess=()=>s[n]=x.result;}tx.oncomplete=()=>r(s);tx.onabort=()=>j(tx.error)});d.close();return {lessons:data.lessons.length,assets:data.assets.length,pending:data.pending.length,journals:data.journal};});}
async function seed(t,values){await t.evaluate(values=>{for(const x of values)localStorage.setItem('lesson:'+x.id,JSON.stringify(x));localStorage.setItem('webLiveLibrary',JSON.stringify(values.map(x=>({id:x.id,title:x.title,subject:x.subject}))));localStorage.setItem('foreign:KEEP','UNCHANGED');},values);await t.evaluate(()=>WebLiveSubjectStorage.refresh().catch(()=>{}));}
async function oldSnapshot(t){return t.evaluate(async()=>{const a={};for(const k of Object.keys(localStorage).filter(k=>k.startsWith('lesson:')||k==='webLiveLibrary'||k.startsWith('foreign:'))){const h=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(localStorage.getItem(k)));a[k]=Array.from(new Uint8Array(h)).join(',');}return a;});}
async function snap(t){return t.evaluate(()=>({id:currentLessonId,activation:lessonActivation,index:i,answerMode,answerStep,showHint,zoom,profile:WebLiveProfiles.getContext().profileId}));}
async function stage(t,x,subject='informatics'){await t.evaluate(()=>showImporter());await t.locator('#lessonSubject').selectOption(subject);await t.locator('#jsonfile').setInputFiles({name:'TEST_ONLY.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(x))});await t.waitForFunction(()=>!document.getElementById('subjectLoadBtn').disabled);}
async function load(t,id){await t.locator('#subjectLoadBtn').click();await t.waitForFunction(id=>currentLessonId===id&&document.getElementById('importer').style.display==='none',id);}
async function corrupt(t,id){await t.evaluate(async id=>{const d=await new Promise(r=>{const q=indexedDB.open('WEB_LIVE_DB');q.onsuccess=()=>r(q.result)});await new Promise((r,j)=>{const tx=d.transaction('lessons','readwrite'),s=tx.objectStore('lessons'),q=s.get(id);q.onsuccess=()=>{const x=q.result;x.body.screens[0].content='CORRUPTION';s.put(x)};tx.oncomplete=r;tx.onabort=()=>j(tx.error)});d.close();},id);}
(async()=>{
 browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});result.browser=browser.version();
 let {c,t}=await fresh();assert.equal((await counts(t)).lessons,0);pass('EMPTY_DATABASE');
 await stage(t,{...tiny,id:'FIRST_NEW',_runtimeSourceKey:undefined});await load(t,'FIRST_NEW');assert.equal((await counts(t)).lessons,1);assert.equal(await t.evaluate(()=>localStorage.getItem('lesson:FIRST_NEW')),null);pass('FIRST_LESSON_SAVE_READBACK_COMMIT');
 await t.evaluate(async tiny=>{await saveLesson({...tiny,id:'SECOND_NEW'});await saveLesson({...tiny,id:'THIRD_NEW'});},tiny);assert.equal((await counts(t)).lessons,3);pass('MULTIPLE_LESSON_SAVE');
 const beforeCount=(await counts(t)).lessons;await stage(t,{...tiny,id:'FIRST_NEW',_runtimeSourceKey:undefined});await load(t,'FIRST_NEW');assert.equal((await counts(t)).lessons,beforeCount);pass('SAME_LESSON_DUPLICATE_IMPORT');
 const changed={...tiny,id:'FIRST_NEW',title:'TEST ONLY changed lesson',screens:[{content:'Updated content'}]};await stage(t,changed);await t.locator('#subjectLoadBtn').click();await t.waitForFunction(()=>currentLessonId.startsWith('FIRST_NEW~'));assert.equal((await counts(t)).lessons,4);pass('LESSON_UPDATE_EXISTING_ID_CONFLICT_POLICY');
 await t.reload();await t.evaluate(()=>WebLiveSubjectStorage.ready);assert.equal((await t.evaluate(()=>getLibrary())).length,4);const reopened=await t.evaluate(()=>WebLiveSubjectStorage.readLesson('FIRST_NEW'));assert.equal(reopened.id,'FIRST_NEW');pass('INDEXEDDB_REOPEN');
 await t.evaluate(()=>WebLiveSubjectStorage.deleteLesson('FIRST_NEW'));assert.equal(await t.evaluate(()=>WebLiveSubjectStorage.readLesson('FIRST_NEW')),null);await t.reload();await t.evaluate(()=>WebLiveSubjectStorage.ready);assert(!await t.evaluate(()=>getLibrary().some(x=>x.id==='FIRST_NEW')));await t.evaluate(()=>showImporter());const recent=await t.locator('#recentLessons').textContent();assert(recent.includes('Bài không còn trong thư viện'));pass('DELETE_INDEXEDDB_LESSON_RECENT_REFERENCE_SAFE');await c.close();

 // Native near/full localStorage quota, existing large image library, active current lesson.
 ({c,t}=await fresh());const imageHeavy=await t.evaluate(async()=>{const response=await fetch('../RC3_PED1_TEST_PACKAGES/TIN6_W04_LIVE_RC3_PED1.zip');const p=await prepareLessonZip(new File([await response.arrayBuffer()],'source.zip'));p.lesson._runtimeSourceKey=p.sourceKey;return p.lesson;});
 await seed(t,[imageHeavy,tiny]);await t.evaluate(async id=>start(await WebLiveSubjectStorage.readLesson(id)),imageHeavy.id);const active=await snap(t);
 const quota=await t.evaluate(()=>{let s='';let hit=false;for(let n=0;n<100;n++){try{s+='x'.repeat(65536);localStorage.setItem('foreign:capacity',s);}catch(e){hit=e.name==='QuotaExceededError';s=s.slice(0,-65536);break;}}for(let chunk of [4096,256,16,1])for(let n=0;n<256;n++)try{s+='x'.repeat(chunk);localStorage.setItem('foreign:capacity',s);}catch(_){s=s.slice(0,-chunk);break;}return {hit,characters:Object.keys(localStorage).reduce((n,k)=>n+k.length+localStorage.getItem(k).length,0)};});assert(quota.hit);pass('EXISTING_LOCALSTORAGE_NEAR_FULL_NATIVE_QUOTA',quota);
 const old=await oldSnapshot(t);await t.evaluate(()=>showImporter());await t.locator('#migrateLegacyStorage').click();await t.waitForFunction(()=>document.getElementById('subjectStorageWarning').textContent.includes('Đã chuyển thư viện an toàn'));assert.deepEqual(await oldSnapshot(t),old);assert.deepEqual(await snap(t),active);let cnt=await counts(t);assert.equal(cnt.lessons,2);assert(cnt.journals.every(j=>j.COMMITTED&&j.TARGET_WRITTEN&&j.TARGET_VERIFIED&&j.CLEANUP_PENDING));pass('LEGACY_LESSON_MIGRATION_READBACK_VERIFY_COMMIT_OLD_PRESERVED',{lessons:cnt.lessons,assets:cnt.assets,journal:cnt.journals});
 await t.evaluate(()=>WebLiveSubjectStorage.migrateLegacyStorage());assert.equal((await counts(t)).lessons,2);assert.deepEqual(await oldSnapshot(t),old);pass('MIGRATION_IDEMPOTENT');
 const newHeavy={...imageHeavy,id:'NEW_IMAGE_HEAVY',title:'TEST ONLY new image-heavy lesson',screens:[...imageHeavy.screens,...imageHeavy.screens]};await stage(t,newHeavy);await load(t,'NEW_IMAGE_HEAVY');assert.equal(await t.evaluate(()=>localStorage.getItem('lesson:NEW_IMAGE_HEAVY')),null);assert.deepEqual(await oldSnapshot(t),old);cnt=await counts(t);assert.equal(cnt.lessons,3);assert.equal(cnt.assets,2);pass('LARGE_IMAGE_MULTIPLE_LARGE_LESSONS_DEDUP_NO_NEW_FULL_PAYLOAD_OR_BASE64_IN_LOCALSTORAGE',{assets:cnt.assets,oldSnapshotUnchanged:true});
 await t.waitForTimeout(100);await t.reload();await t.waitForFunction(()=>currentLessonId==='NEW_IMAGE_HEAVY');pass('FULL_QUOTA_SESSION_REOPEN_USES_INDEXEDDB_STORAGE_BRIDGE');
 const tv=await c.newPage();await tv.goto(base+'/WEB_LIVE/tv.html');await tv.waitForFunction(()=>lastState?.lessonId==='NEW_IMAGE_HEAVY'&&cachedLesson?.id==='NEW_IMAGE_HEAVY'&&!document.getElementById('screen').hidden);assert.equal(await tv.evaluate(()=>localStorage.getItem('lesson:NEW_IMAGE_HEAVY')),null);pass('TV_STANDALONE_REOPEN_NO_LOCALSTORAGE_BACKWRITE');
 const intact=await t.evaluate(id=>WebLiveSubjectStorage.readLesson(id),imageHeavy.id);await corrupt(t,imageHeavy.id);const fallback=await t.evaluate(id=>WebLiveSubjectStorage.readLesson(id),imageHeavy.id);assert.deepEqual(fallback,intact);assert((await t.locator('#subjectStorageWarning').textContent()).includes('Đang dùng bản bài cũ đã kiểm tra'));pass('INDEXEDDB_CORRUPTED_RECORD_VERIFIED_LEGACY_FALLBACK');
 await tv.evaluate(({id,sourceKey})=>{const st=readState();applyState({...st,lessonId:id,lessonSourceKey:sourceKey,lessonActivation:'TV_FALLBACK',stateVersion:999999});},{id:imageHeavy.id,sourceKey:imageHeavy._runtimeSourceKey});await tv.waitForFunction(()=>cachedLesson?.id==='TIN6_T04_P04_SGK_RC3_PED1'&&!document.getElementById('tvStorageWarning').hidden);pass('TV_VISIBLE_VERIFIED_LEGACY_FALLBACK_WARNING');
 await t.evaluate(id=>{const native=IDBObjectStore.prototype.get;window.__get=native;IDBObjectStore.prototype.get=function(key){if(this.name==='lessons'&&key===id)throw new DOMException('Injected read failure','UnknownError');return native.call(this,key)};},tiny.id);assert.equal((await t.evaluate(id=>WebLiveSubjectStorage.readLesson(id),tiny.id)).id,tiny.id);await t.evaluate(()=>{IDBObjectStore.prototype.get=window.__get;});pass('INDEXEDDB_READ_FAILURE_VERIFIED_LEGACY_FALLBACK');
 const current=await snap(t);await t.evaluate(id=>{localStorage.setItem('lesson:'+id,'{"id":"'+id+'","screens":[]}')},imageHeavy.id);await assert.rejects(t.evaluate(id=>WebLiveSubjectStorage.readLesson(id),imageHeavy.id));assert.deepEqual(await snap(t),current);pass('CORRUPTED_TARGET_AND_LEGACY_FAIL_NO_CURRENT_LESSON_LOSS');
 await corrupt(t,'NEW_IMAGE_HEAVY');await assert.rejects(t.evaluate(()=>WebLiveSubjectStorage.readLesson('NEW_IMAGE_HEAVY')));assert.deepEqual(await snap(t),current);pass('NEW_LESSON_CORRUPTION_NO_SILENT_FALLBACK');await t.screenshot({path:out+'/FULL_QUOTA_SAFE_CURRENT.png'});await c.close();

 // Injected failures are separate from native quota evidence above.
 ({c,t}=await fresh());await seed(t,[tiny]);await t.evaluate(async()=>start(await WebLiveSubjectStorage.readLesson('OLD_SMALL')));const old2=await oldSnapshot(t),current2=await snap(t);
 await t.evaluate(()=>{const put=IDBObjectStore.prototype.put;window.__put=put;IDBObjectStore.prototype.put=function(...args){if(this.name==='pending')throw new DOMException('Injected quota','QuotaExceededError');return put.apply(this,args)};});await assert.rejects(t.evaluate(()=>WebLiveSubjectStorage.migrateLegacyLesson('OLD_SMALL')));assert.equal((await counts(t)).lessons,0);assert.deepEqual(await oldSnapshot(t),old2);assert.deepEqual(await snap(t),current2);pass('MIGRATION_WRITE_QUOTA_FAILURE_OLD_CURRENT_PRESERVED');
 await stage(t,{...tiny,id:'FAILED_NEW'});await t.locator('#subjectLoadBtn').click();await t.waitForFunction(()=>document.getElementById('error').textContent.includes('Không nạp được bài'));assert.deepEqual(await snap(t),current2);assert.equal((await counts(t)).lessons,0);pass('NEW_IMPORT_WRITE_FAILURE_NO_FALSE_SUCCESS');await t.evaluate(()=>{IDBObjectStore.prototype.put=window.__put;});
 await t.evaluate(()=>{const get=IDBObjectStore.prototype.get;window.__get=get;IDBObjectStore.prototype.get=function(...args){if(this.name==='pending')throw new DOMException('Injected verification read failure','UnknownError');return get.apply(this,args)};});await assert.rejects(t.evaluate(()=>WebLiveSubjectStorage.migrateLegacyLesson('OLD_SMALL')));cnt=await counts(t);assert.equal(cnt.lessons,0);assert.equal(cnt.pending,1);assert(!cnt.journals[0].COMMITTED);assert.deepEqual(await oldSnapshot(t),old2);pass('MIGRATION_READ_FAILURE_NO_COMMIT');await t.evaluate(()=>{IDBObjectStore.prototype.get=window.__get;});await t.evaluate(()=>WebLiveSubjectStorage.migrateLegacyLesson('OLD_SMALL'));assert.equal((await counts(t)).pending,0);pass('TARGET_PARTIAL_REWRITE_WITHOUT_DUPLICATE_STAGE');
 // Abort after requests succeed must roll back deletion and journal together.
 await t.evaluate(()=>{const tx=IDBDatabase.prototype.transaction;window.__tx=tx;IDBDatabase.prototype.transaction=function(stores,mode){const x=tx.apply(this,arguments);if(mode==='readwrite'&&Array.from(x.objectStoreNames).includes('lessons')&&Array.from(x.objectStoreNames).includes('assets'))queueMicrotask(()=>x.abort());return x};});await assert.rejects(t.evaluate(()=>WebLiveSubjectStorage.deleteLesson('OLD_SMALL')));await t.evaluate(()=>{IDBDatabase.prototype.transaction=window.__tx;});assert.equal((await t.evaluate(()=>WebLiveSubjectStorage.readLesson('OLD_SMALL'))).id,'OLD_SMALL');pass('TRANSACTION_ABORT_DATA_LOSS_TEST');
 await t.evaluate(()=>WebLiveSubjectStorage.deleteLesson('OLD_SMALL'));assert.equal(await t.evaluate(()=>localStorage.getItem('lesson:OLD_SMALL')),JSON.stringify(tiny));assert.equal(await t.evaluate(()=>WebLiveSubjectStorage.readLesson('OLD_SMALL')),null);await t.reload();await t.evaluate(()=>WebLiveSubjectStorage.ready);assert.equal(await t.evaluate(()=>WebLiveSubjectStorage.readLesson('OLD_SMALL')),null);assert.deepEqual(await oldSnapshot(t),old2);pass('DELETE_MIGRATED_IDB_LESSON_TOMBSTONE_OLD_COPY_RETAINED');await c.close();

 ({c,t}=await fresh());await seed(t,[tiny]);const beforeClose=await oldSnapshot(t);await t.evaluate(()=>{const native=IDBDatabase.prototype.transaction;IDBDatabase.prototype.transaction=function(stores,mode){const tx=native.apply(this,arguments);if(mode==='readonly'&&Array.from(tx.objectStoreNames).includes('pending')){window.__migrationHeld=true;Object.defineProperty(tx,'oncomplete',{set(){},get(){return null}});}return tx;};WebLiveSubjectStorage.migrateLegacyLesson('OLD_SMALL').catch(()=>{});});await t.waitForFunction(()=>window.__migrationHeld===true);await t.close();t=await c.newPage();await t.goto(base+'/WEB_LIVE/teacher.html');await t.evaluate(()=>WebLiveSubjectStorage.ready);cnt=await counts(t);assert.equal(cnt.lessons,0);assert.equal(cnt.pending,1);assert(cnt.journals[0].TARGET_WRITTEN&&!cnt.journals[0].COMMITTED);assert.deepEqual(await oldSnapshot(t),beforeClose);await t.evaluate(()=>WebLiveSubjectStorage.migrateLegacyLesson('OLD_SMALL'));cnt=await counts(t);assert.equal(cnt.lessons,1);assert.equal(cnt.pending,0);assert(cnt.journals[0].COMMITTED);pass('BROWSER_CLOSE_DURING_MIGRATION_INTERRUPTION_RECOVERY');await c.close();

 // Open failure and blocked connection: independently fresh contexts, no DB deletion/LS clear.
 const deny=()=>{const native=indexedDB.open.bind(indexedDB);indexedDB.open=function(...args){if(args[0]==='WEB_LIVE_DB')throw new DOMException('Injected open denied','SecurityError');return native(...args)};};({c,t}=await fresh(deny));await seed(t,[tiny]);assert.equal((await t.evaluate(()=>WebLiveSubjectStorage.readLesson('OLD_SMALL'))).id,'OLD_SMALL');await stage(t,{...tiny,id:'DENIED_NEW'});await t.locator('#subjectLoadBtn').click();await t.waitForFunction(()=>document.getElementById('error').textContent.includes('Không nạp được'));assert.equal(await t.evaluate(()=>localStorage.getItem('lesson:DENIED_NEW')),null);pass('INDEXEDDB_OPEN_FAILURE_CONTROLLED_LEGACY_FALLBACK_NO_FALSE_SAVE');await c.close();
 const blocked=()=>{const native=indexedDB.open.bind(indexedDB);indexedDB.open=function(...args){if(args[0]!=='WEB_LIVE_DB')return native(...args);const request={};setTimeout(()=>request.onblocked?.(),0);return request;};};({c,t}=await fresh(blocked));assert.equal(await t.evaluate(()=>WebLiveSubjectStorage.getStorageHealth().status),'DB_UNAVAILABLE');assert.equal(await t.evaluate(()=>lesson),null);pass('INDEXEDDB_BLOCKED_TIMEOUT_NO_CRASH');await c.close();
 assert.deepEqual(result.errors,[]);pass('ZERO_UNHANDLED_BROWSER_ERRORS');result.result='PASS';fs.writeFileSync(out+'/STORAGE_RESULTS.json',JSON.stringify(result,null,2)+'\n');await browser.close();console.log(JSON.stringify({result:'PASS',checks:result.checks.length}));
})().catch(async e=>{result.result='FAIL';result.error={message:e.message,stack:e.stack};fs.writeFileSync(out+'/STORAGE_RESULTS.json',JSON.stringify(result,null,2)+'\n');await browser?.close();console.error(e);process.exitCode=1;});
