
let lesson=null,currentLessonId='',lessonActivation='',stateVersion=0,i=0,showHint=false,answerMode='hidden',answerStep=0,analysisStep=0,tvWindow=null,viewMode='text',zoom=1,pointer=null,pan={x:0,y:0},drag=null,boardController=null,coverController=null,smartController=null,classroomController=null,pedagogyController=null,hintLevel=0,knowledgeCloseVisible=false;
const $=id=>document.getElementById(id);
function paintMath(id,value){const el=$(id);if(typeof renderMathAtomic==='function')renderMathAtomic(el,value);else el.textContent=value}
const sample={id:'HINH8_V04_MAU',subject:'Hình học 8',week:4,period:7,title:'Mẫu Geometry Mode',screens:[{type:'Ví dụ',title:'Quan sát hình',content:'Cho ABCD là hình bình hành.\nHãy xác định hai cặp cạnh đối.',hint:'Quan sát các cạnh không có đỉnh chung.',answer:'AB ∥ CD\nAD ∥ BC',teacherNote:'Bấm lên hình để đặt điểm chỉ.',image:''},{type:'Chứng minh',title:'Chọn dấu hiệu',content:'Muốn chứng minh một tứ giác là hình bình hành, ta có thể chứng minh điều gì?',hint:'Có thể dùng dấu hiệu theo cạnh.',answer:'Hai cặp cạnh đối bằng nhau.\nHoặc một cặp cạnh đối vừa song song vừa bằng nhau.',teacherNote:'Có thể hiện lời giải theo từng bước.'}]};
sample.screens[0].imageData='data:image/svg+xml;base64,'+btoa('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 600 400"><rect width="600" height="400" fill="white"/><path d="M130 320 390 320 490 80 230 80Z" fill="none" stroke="#17253d" stroke-width="6"/><g fill="#17253d" font-size="38" font-family="Arial"><text x="88" y="360">A</text><text x="395" y="365">B</text><text x="500" y="88">C</text><text x="190" y="80">D</text></g></svg>');
function valid(x){return x&&Array.isArray(x.screens)&&x.screens.length}
function currentImage(){return resolveScreenImage(lesson,i)}
function currentAnalysisDiagram(){return resolveAnalysisDiagram(lesson,i)}
function resetView(){let s=lesson?.screens?.[i],img=!!currentImage(),analysis=img&&(isAnalysisScreen(s)||!!currentAnalysisDiagram());showHint=false;hintLevel=0;knowledgeCloseVisible=false;answerMode='hidden';answerStep=0;analysisStep=0;zoom=1;pan={x:0,y:0};pointer=null;viewMode=analysis?'split':img&&['split','figure','text'].includes(s.layout)?s.layout:img?'split':'text'}
function start(x,resume=null){
 window.ttsUI?.cancel('Đã dừng để mở bài.');
 boardController?.cancelPending();coverController?.cancelPending();smartController?.cancelPending();
 resetSceneIndex(lesson);drag=null;pointer=null;lesson=null;currentLessonId='';
 lesson=x;currentLessonId=x.id||x.packageId||'';i=resume&&Number.isInteger(resume.index)&&resume.index>=0&&resume.index<x.screens.length?resume.index:0;
 lessonActivation=globalThis.crypto?.randomUUID?.()||Date.now().toString(36)+'-'+(++stateVersion);
 rebuildSceneIndex(x);resetView();
 boardController?.lessonChanged();coverController?.lessonChanged();smartController?.lessonChanged();classroomController?.lessonChanged();
 if(resume?.clock&&classroomController){const c=resume.clock;if(['off','clock','timer'].includes(c.mode)&&[45,90].includes(c.durationMin)&&Number.isFinite(c.elapsedMs)&&c.elapsedMs>=0&&Number.isFinite(c.startedAt)&&typeof c.running==='boolean')classroomController.clock={mode:c.mode,durationMin:c.durationMin,elapsedMs:c.elapsedMs,startedAt:c.startedAt,running:c.running};}
 hideImporter();populateJump();render();sync();
}
function populateJump(){let j=$('jump');j.innerHTML=lesson.screens.map((s,n)=>`<option value="${n}">${n+1}. ${esc(s.title||s.type||'Màn hình')}</option>`).join('');j.value=i}
$('jsonfile').onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=async()=>{try{let x=validateLesson(JSON.parse(r.result));let missing=x.screens.flatMap(s=>[['image','imageData'],['geometryImage','geometryImageData'],['analysisImage','analysisImageData'],['analysisDiagram','analysisDiagramData']].filter(([a,b])=>{let path=assetPath(s[a]);return path&&!s[b]&&!s[a]?.imageData&&!s[a]?.data&&!path.startsWith('data:image/')}).map(([a])=>assetPath(s[a])));if(missing.length)throw Error('Ảnh cần nhập bằng LIVE.zip: '+[...new Set(missing)].join(', '));await saveLesson(x);$('error').textContent='';renderLibrary();start(x)}catch(err){$('error').textContent='Không đọc được lesson.json: '+err.message}};r.onerror=()=>{$('error').textContent='Không đọc được tệp JSON'};r.readAsText(f,'utf-8');e.target.value=''};
$('zipfile').onchange=async e=>{let f=e.target.files[0];if(!f)return;try{$('error').textContent='Đang nhập gói…';let x=await importZip(f);$('error').textContent='';renderLibrary();start(x)}catch(err){$('error').textContent='Không nhập được ZIP: '+err.message}e.target.value=''};
async function loadSample(){await saveLesson(sample);renderLibrary();start(sample)}
function render(){if(!lesson)return;globalThis.WebLiveProfiles?.observe('teacher',lesson,{lessonId:currentLessonId,lessonActivation,lessonSourceKey:lesson._runtimeSourceKey||'',index:i,stateVersion});let s=lesson.screens[i],resolved=currentImage(),diagram=currentAnalysisDiagram(),img=!!resolved,analysis=img&&(isAnalysisScreen(s)||!!diagram),steps=liveAnalysisSteps(s);if(analysis&&viewMode==='text')viewMode='split';$('kind').textContent=s.type||'LIVE';$('screenNo').textContent=`${i+1}/${lesson.screens.length}`;$('lessonTitle').textContent=lesson.title||'';paintMath('title',normalizeLiveText(s.title||'','title'));paintMath('content',normalizeLiveText(livePedagogyContent(lesson,s,knowledgeCloseVisible),'prose'));$('content').hidden=livePedagogyIsClose(lesson,s)&&!knowledgeCloseVisible;paintMath('hint',normalizeLiveText(s.hint||'','hint')||'—');paintMath('answer',liveAnswerText(s,'full')||'—');paintMath('analysisBox',liveAnalysisText(s,steps.length)||'—');$('analysisSection').hidden=!steps.length;$('analysisBtn').hidden=!steps.length;$('note').textContent=s.teacherNote||s.note||'—';$('progress').textContent=`${lesson.subject||''} • Tuần ${lesson.week??'-'} • Tiết ${lesson.period??'-'}`;$('jump').value=i;let ns=lesson.screens[i+1];$('nextBox').textContent=ns?`${i+2}. ${normalizeLiveText(ns.title||ns.type||'Màn hình tiếp theo','title')}`:'Hết tiết';
 let scr=$('screen'),fp=$('figurePane'),p=$('pic');scr.className='screen '+(img?'hasImage':'textOnly')+(img&&viewMode!=='split'?' '+viewMode:'')+(analysis?' analysis':'');fp.hidden=!img;$('geometryTools').style.display=img?'block':'none';$('imageStatus').hidden=true;if(img){if(p.src!==resolved.imageData){p.onload=applyZoom;p.onerror=()=>{$('imageStatus').hidden=false;$('imageStatus').textContent='Không đọc được ảnh: '+(resolved.image||'ảnh nhúng')};p.src=resolved.imageData}requestAnimationFrame(applyZoom)}else{p.removeAttribute('src')}
 let af=$('analysisFigure'),ap=$('analysisPic');af.hidden=!diagram||!!steps.length;if(diagram&&!steps.length){if(ap.src!==diagram.imageData)ap.src=diagram.imageData}else ap.removeAttribute('src');
 paintMath('previewAnalysis',liveAnalysisText(s,analysisStep));$('previewAnalysis').hidden=!analysisStep;let ht=livePedagogyEnabled(lesson)?livePedagogyHint(s,hintLevel):s.hint||'';paintMath('previewHint',normalizeLiveText(ht,'hint'));$('previewHint').hidden=!showHint||!ht;let at=answerTextForState(s);paintMath('previewAnswer',at);$('previewAnswer').hidden=!at;renderPointer();renderButtons();boardController?.render();coverController?.render();smartController?.render();classroomController?.render();pedagogyController?.render(s);if(typeof demoController!=='undefined')demoController.render(s);window.cockpit?.refresh();window.ttsUI?.refresh();}
function answerTextForState(s){return liveAnswerText(s,answerMode,answerStep)}
function renderButtons(){$('hintBtn').classList.toggle('active',showHint);$('ansBtn').classList.toggle('active',answerMode==='full');['split','figure','text'].forEach(m=>$(m+'Btn')?.classList.toggle('active',viewMode===m));let analysis=!!currentImage()&&(isAnalysisScreen(lesson?.screens?.[i])||!!currentAnalysisDiagram());$('figureBtn').disabled=false;$('textBtn').disabled=analysis;$('zoomLabel').textContent=Math.round(zoom*100)+'%'}
function applyZoom(){let p=$('pic'),pane=$('figurePane'),inner=$('figureInner');if(!p.naturalWidth||!pane.clientWidth)return;let w=pane.clientWidth-20,h=pane.clientHeight-20,k=Math.min(w/p.naturalWidth,h/p.naturalHeight);let fw=p.naturalWidth*k,fh=p.naturalHeight*k;inner.style.width=fw+'px';inner.style.height=fh+'px';let rx=Math.max(0,(fw*zoom-w)/2),ry=Math.max(0,(fh*zoom-h)/2);inner.style.transform=`translate(${pan.x*rx}px,${pan.y*ry}px) scale(${zoom})`;renderPointer();boardController?.renderOverlay();coverController?.render();smartController?.render();classroomController?.fit()}
function renderPointer(){let el=$('pointer');if(pointer&&currentImage()){el.style.left=(pointer.x*100)+'%';el.style.top=(pointer.y*100)+'%';el.hidden=false}else el.hidden=true;$('clearPointerTop').disabled=!pointer}
$('figurePane').addEventListener('pointerdown',e=>{if(!lesson||!currentImage()||(boardController?.editingOverlay()||coverController?.editing()||smartController?.editing()))return;drag={x:e.clientX,y:e.clientY,start:{...pan},moved:false};$('figurePane').setPointerCapture(e.pointerId)});
$('figurePane').addEventListener('pointermove',e=>{if((boardController?.editingOverlay()||coverController?.editing()||smartController?.editing())||!drag||zoom<=1)return;let dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.abs(dx)+Math.abs(dy)>4)drag.moved=true;if(!drag.moved)return;let p=$('pic'),pane=$('figurePane'),rx=Math.max(0,(p.clientWidth*zoom-(pane.clientWidth-20))/2),ry=Math.max(0,(p.clientHeight*zoom-(pane.clientHeight-20))/2);pan={x:rx?Math.max(-1,Math.min(1,drag.start.x+dx/rx)):0,y:ry?Math.max(-1,Math.min(1,drag.start.y+dy/ry)):0};pane.classList.add('dragging');applyZoom();sync()});
$('figurePane').addEventListener('pointerup',e=>{if((boardController?.editingOverlay()||coverController?.editing()||smartController?.editing())||!drag)return;let moved=drag.moved;drag=null;$('figurePane').classList.remove('dragging');if(moved||!e.shiftKey)return;let img=$('pic'),r=img.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)return;pointer={x:Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),y:Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))};renderPointer();sync()});
function state(){let s=lesson.screens[i];return{type:'state',lessonId:currentLessonId,lessonSourceKey:lesson._runtimeSourceKey||'',lessonActivation,stateVersion:++stateVersion,sceneId:resolveScreenVisuals(lesson,i)?.sceneId||'',lesson:{subject:lesson.subject,week:lesson.week,period:lesson.period,title:lesson.title},index:i,total:lesson.screens.length,pedagogy:livePedagogyState(lesson,hintLevel,knowledgeCloseVisible),showHint,answerMode,answerStep,analysisStep,viewMode,zoom,pan,pointer,board:boardController?.summary()||null,cover:coverController?.summary()||null,smart:smartController?.summary()||null,classroom:classroomController?.state()||null,screenLite:{title:s?.title||''}}}
function sync(){if(!lesson)return;const st=state();globalThis.WebLiveProfiles?.present('teacher',lesson,st,$('screen'));storeState(st);send(st);try{if(tvWindow&&!tvWindow.closed)tvWindow.postMessage(st,'*');document.getElementById('studentPreview')?.contentWindow?.postMessage(st,location.origin==='null'?'*':location.origin)}catch(_){}window.cockpit?.refresh()}
function go(n){if(!lesson)return;window.ttsUI?.cancel();i=Math.max(0,Math.min(lesson.screens.length-1,n));resetView();boardController?.screenChanged();coverController?.screenChanged();smartController?.screenChanged();classroomController?.screenChanged();render();sync()}
function next(){if(lesson&&i<lesson.screens.length-1)go(i+1)}function prev(){if(lesson&&i>0)go(i-1)}function jumpTo(v){go(Number(v)||0)}
function toggleHint(){if(!lesson)return;if(livePedagogyEnabled(lesson)){hintLevel=hintLevel?0:1;showHint=hintLevel>0}else showHint=!showHint;render();sync()}
function toggleAnswer(){if(!lesson)return;answerMode=answerMode==='full'?'hidden':'full';answerStep=0;render();sync()}
function revealStep(){if(!lesson)return;let n=liveSteps(lesson.screens[i]).length;if(!n)return;answerMode='steps';answerStep=Math.min(n,answerStep+1||1);render();sync()}
function revealAnalysis(){if(!lesson)return;let n=liveAnalysisSteps(lesson.screens[i]).length;if(!n)return;analysisStep=Math.min(n,analysisStep+1);render();sync()}
function previousStep(){if(!lesson)return;answerStep=Math.max(0,answerStep-1);answerMode=answerStep?'steps':'hidden';render();sync()}
function hideAnswer(){answerMode='hidden';answerStep=0;render();sync()}
function setMode(m){if(!lesson||(!currentImage()&&m!=='text')||(currentImage()&&(isAnalysisScreen(lesson.screens[i])||currentAnalysisDiagram()||(boardController?.editingOverlay()||coverController?.editing()||smartController?.editing()))&&m==='text'))return;viewMode=m;render();sync()}
function zoomBy(d){if(!lesson||!currentImage())return;zoom=Math.max(.7,Math.min(2,Math.round((zoom+d)*100)/100));applyZoom();renderButtons();sync()}
function resetZoom(){zoom=1;pan={x:0,y:0};applyZoom();renderButtons();sync()}
function clearPointer(){pointer=null;renderPointer();sync()}
function openTV(){tvWindow=window.open('tv.html','WEB_LIVE_TV','width=1280,height=720');setTimeout(sync,350);setTimeout(sync,900);tvWindow?.focus()}
function showImporter(){window.ttsUI?.cancel('Đã dừng để chọn bài.');$('importer').style.display='flex';renderLibrary()}function hideImporter(){$('importer').style.display='none'}
function renderLibrary(){let lib=getLibrary(),el=$('library');if(!lib.length){el.innerHTML='<p class="muted">Chưa có tiết dạy đã lưu.</p>';return}el.innerHTML=lib.map(x=>`<div class="item"><div><b>${esc(x.title)}</b><div class="small">${esc(x.subject)} • Tuần ${esc(x.week)} • Tiết ${esc(x.period)}</div></div><div><button onclick="openSaved('${jsq(x.id)}')">MỞ</button> <button onclick="removeSaved('${jsq(x.id)}')">XÓA</button></div></div>`).join('')}
function jsq(v){return String(v).replace(/\\/g,'\\\\').replace(/'/g,"\\'")}async function openSaved(id){try{const x=await WebLiveSubjectStorage.readLesson(id);if(x)start(x)}catch(e){$('error').textContent=e.message}}async function removeSaved(id){if(confirm('Xóa bài này khỏi thư viện IndexedDB? Bản localStorage cũ vẫn giữ nguyên.'))try{await deleteLesson(id);renderLibrary()}catch(e){$('error').textContent=e.message}}
function onPeer(d,source){if(d?.type==='classroomToggleFigure'&&lesson&&d.lessonId===currentLessonId&&d.lessonActivation===lessonActivation){classroomController?.toggleFigure();return}if(d?.type==='ready'){sync();return}if(d?.type==='needDrawBoard'&&lesson&&d.lessonId===currentLessonId){boardController?.snapshot(d.scope,source);return}if(d?.type==='needCoverLayer'&&lesson&&d.lessonId===currentLessonId){coverController?.snapshot(d.scope,source);return}if(d?.type==='needSmartGeometry'&&lesson&&d.lessonId===currentLessonId){smartController?.snapshot(d.scope,source);return}if(d?.type==='needLesson'&&lesson&&d.lessonId===currentLessonId&&(!d.lessonActivation||d.lessonActivation===lessonActivation)){let response={type:'lesson',lesson,lessonActivation};if(source?.postMessage)source.postMessage(response,'*');else send(response)}}
if(bc)bc.onmessage=e=>onPeer(e.data);window.addEventListener('message',e=>onPeer(e.data,e.source));
document.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(document.activeElement.tagName))return;if(e.key==='ArrowRight')next();else if(e.key==='ArrowLeft')prev();else if(e.key.toLowerCase()==='g')toggleHint();else if(e.key.toLowerCase()==='a')toggleAnswer();else if(e.key.toLowerCase()==='s')revealStep();else if(e.key.toLowerCase()==='f')setMode('figure');else if(e.key.toLowerCase()==='t')setMode('text');else if(e.key.toLowerCase()==='d')setMode('split');else if(e.key==='+'||e.key==='=')zoomBy(.15);else if(e.key==='-')zoomBy(-.15)});
window.addEventListener('resize',applyZoom);renderLibrary();boardController=new DrawBoardTeacher();coverController=typeof CoverLayerTeacher!=='undefined'?new CoverLayerTeacher():null;smartController=typeof SmartGeometryTeacher!=='undefined'?new SmartGeometryTeacher():null;
