const {chromium}=require('playwright');const fs=require('fs');const path=require('path');const assert=require('assert');
const root=process.env.WEB_LIVE_TEST_ROOT||path.resolve(__dirname,'..'),out="/workspace/WEB_LIVE_MULTI_SUBJECT_PHASE1/evidence/ENGINE_AUDIT";fs.mkdirSync(out,{recursive:true});
const base='http://127.0.0.1:8770/WEB_LIVE/';
(async()=>{
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',headless:true,args:['--no-sandbox']});const ctx=await browser.newContext({viewport:{width:1366,height:768}});const errors=[],external=[];
ctx.on('page',p=>p.on('pageerror',e=>errors.push(e.message)));await ctx.route('**/*',route=>{if(!route.request().url().startsWith('http://127.0.0.1:8770/')&&!route.request().url().startsWith('data:')){external.push(route.request().url());return route.abort()}return route.continue()});
const teacher=await ctx.newPage();await teacher.goto(base+'teacher.html');const tv=await ctx.newPage();await tv.goto(base+'tv.html');
const results={browser:browser.version(),real:[],visual:[],assertions:[],errors,external};
async function settled(){await tv.waitForTimeout(90);await tv.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));}
async function snapshot(){return tv.evaluate(()=>{const scr=document.getElementById('screen'),pane=scr.querySelector('.textPane'),fig=document.getElementById('figurePane');return {mode:scr.dataset.subjectMode,kind:scr.dataset.algebraKind,overflow:pane.scrollHeight>pane.clientHeight+2,horizontal:pane.scrollWidth>pane.clientWidth+2,height:pane.clientHeight,scroll:pane.scrollHeight,figure:fig.getBoundingClientRect().width,text:pane.getBoundingClientRect().width,content:document.getElementById('content').innerText,answer:document.getElementById('answer').innerText,analysis:document.getElementById('analysis').innerText,pic:document.getElementById('pic').getAttribute('src'),steps:scr.querySelectorAll('#answer .proofStep').length,analysisSteps:scr.querySelectorAll('#analysis .analysisStep').length,options:scr.querySelectorAll('.tvOptionCard').length}})}
async function loadPackage(rel){console.log('Import',rel);await teacher.evaluate(()=>localStorage.clear());await teacher.locator('#zipfile').setInputFiles(root+'/'+rel);try{await teacher.waitForFunction(()=>document.getElementById('importer').style.display==='none'&&document.getElementById('error').textContent==='',{},{timeout:5000})}catch(e){console.log(await teacher.locator('#error').textContent());throw e;}await settled();return teacher.evaluate(()=>JSON.parse(JSON.stringify(lesson)))}
async function go(i,state={}){await teacher.evaluate(({i,state})=>{go(i);if(state.full)toggleAnswer();for(let n=0;n<(state.steps||0);n++)revealStep();for(let n=0;n<(state.analysis||0);n++)revealAnalysis();if(state.knowledge){knowledgeCloseVisible=true;render();sync()}}, {i,state});await settled();}
async function shot(name,source,extra={}){await settled();const data=await snapshot();await tv.screenshot({path:out+'/'+name+'.png'});const {pic,...metrics}=data;results.visual.push({name,source,viewport:tv.viewportSize(),...extra,...metrics,imageSha256:pic?require('crypto').createHash('sha256').update(pic).digest('hex'):null});}
const tin=await loadPackage('RC3_PED1_TEST_PACKAGES/TIN6_W04_LIVE_RC3_PED1.zip');
for(const [name,i,st] of [['TIN_01_REVIEW',1,{}],['TIN_02_INTRO',2,{}],['TIN_03_MCQ',14,{}],['TIN_04_OBSERVE',12,{}],['TIN_05_KNOWLEDGE',5,{knowledge:true}],['TIN_06_PRACTICE',30,{}],['TIN_07_APPLICATION',34,{}]]){await go(i,st);await shot(name,'TIN6_W04 real package');}
await go(14);assert.equal((await snapshot()).options,4);results.assertions.push('Real TIN6 MCQ: four option cards');
await go(5);assert.equal(await tv.locator('#content').isVisible(),false);await go(5,{knowledge:true});assert.equal(await tv.locator('#content').isVisible(),true);results.assertions.push('Knowledge disclosure retained');
for(const rel of ['RC3_PED1_TEST_PACKAGES/TIN6_W04_LIVE_RC3_PED1.zip','RC3_PED1_TEST_PACKAGES/TIN6_W05_LIVE_RC3_PED1.zip','RC3_PED1_TEST_PACKAGES/TIN8_W04_LIVE_RC3_PED1.zip','WEB_LIVE/HINH_HOC_8_T04_T07_LIVE_TEST.zip','WEB_LIVE/HINH_HOC_8_T04_T07_DUAL_VISUAL_TEST.zip']){
 const l=await loadPackage(rel),before=JSON.stringify(l),states=[];
 for(let i=0;i<l.screens.length;i++){await go(i);let s=await snapshot();states.push({index:i,type:l.screens[i].type,stage:'question',overflow:s.overflow,horizontal:s.horizontal});await go(i,{full:true,analysis:(l.screens[i].analysisSteps||[]).length});s=await snapshot();states.push({index:i,stage:'full',overflow:s.overflow,horizontal:s.horizontal});}
 assert.equal(await teacher.evaluate(()=>JSON.stringify(lesson)),before);results.real.push({package:rel,screens:l.screens.length,states,lessonUnchanged:true});
}
const geo=await loadPackage('WEB_LIVE/HINH_HOC_8_T04_T07_DUAL_VISUAL_TEST.zip');
for(const [name,i,st] of [['GEO_01_STATEMENT',5,{}],['GEO_02_OBSERVE',6,{}],['GEO_03_ANALYSIS',7,{analysis:2}],['GEO_05_PROOF_STEP_1',8,{steps:1}],['GEO_06_PROOF_STEP_2',8,{steps:2}],['GEO_07_CONCLUSION',10,{full:true}]]){await go(i,st);await shot(name,'HINH_HOC_8_T04_T07_DUAL_VISUAL_TEST real package');}
await go(7,{analysis:1});const fig=(await snapshot()).pic;await go(7,{analysis:2});assert.equal((await snapshot()).pic,fig);assert.equal((await snapshot()).analysisSteps,2);results.assertions.push('Geometry scene retained across progressive analysis');
await go(8,{steps:1});assert.equal((await snapshot()).steps,1);await teacher.evaluate(()=>previousStep());await settled();assert.equal(await tv.locator('#answer').isVisible(),false);results.assertions.push('Proof reveal and previousStep hide');
await go(5);await teacher.evaluate(()=>{classroomController.focus={region:'content',index:0};pointer={x:.2,y:.3};zoom=1.2;sync()});await settled();assert.equal(await tv.locator('#pointer').isVisible(),true);assert.equal(await tv.locator('#pointer').evaluate(e=>e.style.left),'20%');results.assertions.push('Pointer and zoom state received');
assert.deepEqual(await tv.locator('#figureInner').evaluate(e=>[...e.children].map(n=>n.id)),['pic','coverLayer','smartLayer','drawOverlay','classroomHighlight','pointer']);results.assertions.push('Overlay order unchanged');
await teacher.evaluate(()=>{boardController.model(boardController.overlayKey()).add({type:'segment',x1:.1,y1:.2,x2:.7,y2:.3});coverController.model().add({type:'coverRect',x:.1,y:.1,w:.2,h:.15});smartController.model().add({type:'parallelMark',lines:[{kind:'anchors',a:{x:.1,y:.2},b:{x:.7,y:.3}}],styleIndex:1});classroomController.highlights=[{type:'segment',points:[{x:.2,y:.2},{x:.5,y:.5}]}];classroomController.focus={region:'content',index:0};render();sync()});await settled();
assert(await tv.locator('#drawOverlay [data-object-id]').count()>0);assert(await tv.locator('#coverLayer [data-cover-id]').count()>0);assert(await tv.locator('#smartLayer [data-smart-id]').count()>0);assert(await tv.locator('#classroomHighlight line').count()>0);assert(await tv.locator('#content .isFocused').count()>0);results.assertions.push('Draw Board, Cover, Smart Geometry, Highlight and Focus render real runtime records');
await teacher.evaluate(()=>classroomController.startTimer());await settled();assert(await tv.locator('#classroomClock').isVisible());assert((await tv.locator('#classroomClock').innerText()).includes('/ 45:00'));await teacher.evaluate(()=>classroomController.pauseTimer());results.assertions.push('Timer sync');
await teacher.evaluate(()=>boardController.selectMode('whiteboard'));await settled();assert(await tv.locator('#whiteBoardPane').isVisible());assert(!await tv.locator('#screen').isVisible());await teacher.evaluate(()=>boardController.close());await settled();assert(await tv.locator('#screen').isVisible());results.assertions.push('Whiteboard open/close');
await teacher.evaluate(()=>classroomController.setLayout('70'));await settled();assert((await snapshot()).figure>(await snapshot()).text*2);await tv.locator('#figurePane').dblclick();await settled();assert(!await tv.locator('.textPane').isVisible());await tv.locator('#figurePane').dblclick();await settled();assert(await tv.locator('.textPane').isVisible());results.assertions.push('70/30 preset and TV double-click Teacher round-trip');
// Presentation fixtures are deliberately not lesson packages or claimed curriculum sources.
const svg='data:image/svg+xml;base64,'+Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 600 400"><rect width="600" height="400" fill="white"/><path d="M70 330H550 M110 350V40 M110 290L500 80" stroke="#1b3956" stroke-width="5" fill="none"/><text x="490" y="110" font-size="30">y = 2x</text></svg>').toString('base64');
const fixtures=[
['TIN_08_PRACTICAL','Tin học 6',{type:'PRACTICAL',title:'Thực hành',content:'Tạo thư mục và lưu tệp vào thư mục đã chọn.'}],
['TIN_09_DEMO','Tin học 6',{type:'DEMO',title:'Demo trực tiếp',content:'Quan sát thao tác và thực hiện trên máy.',demo:{appId:'word'}}],
['ALG_01_EXPRESSION','Đại số 8',{type:'EXPRESSION',title:'Rút gọn',content:'A = 3x(x - 2) - 2x(x + 1)',steps:['3x(x - 2) = 3x² - 6x','-2x(x + 1) = -2x² - 2x','A = x² - 8x']}],
['ALG_02_EQUATION','Đại số 8',{type:'EQUATION',title:'Giải phương trình',content:'2x - 5 = 9',steps:['2x - 5 = 9','2x = 14','x = 7']}],
['ALG_03_SYSTEM','Đại số 8',{type:'SYSTEM',title:'Giải hệ phương trình',content:'2x + y = 5\nx - y = 1',steps:['3x = 6','x = 2','y = 1']}],
['ALG_04_WORD_PROBLEM','Đại số 8',{type:'WORD_PROBLEM',title:'Phân tích bài toán',content:'Đặt ẩn: x = chiều rộng\nĐiều kiện: x > 0\nBiểu diễn: chiều dài = x + 4\nPhương trình: x(x + 4) = 60'}],
['ALG_05_IDENTITY','Đại số 8',{type:'IDENTITY',title:'Chứng minh đẳng thức',content:'(x + 1)² - x² = 2x + 1',steps:['(x + 1)² - x²','x² + 2x + 1 - x²','2x + 1']}],
['ALG_06_TABLE','Đại số 8',{type:'TABLE',title:'Đọc bảng số liệu',content:'| Điểm | 6 | 7 | 8 |\n| --- | --- | --- | --- |\n| Số học sinh | 4 | 6 | 10 |\nCó bao nhiêu học sinh được điểm 8?'}],
['ALG_07_GRAPH','Đại số 8',{type:'GRAPH',title:'Quan sát đồ thị',content:'Đọc giá trị y khi x = 2.',imageData:svg,visualRole:'illustration'}],
['ALG_08_PRACTICE','Đại số 8',{type:'PRACTICE',title:'Luyện tập',content:'Rút gọn biểu thức:\nB = 2x(x + 3) - x²',steps:['B = 2x² + 6x - x²','B = x² + 6x']}],
['GEO_04_DEPENDENCY_TREE','Hình học 8',{type:'PROOF_DEPENDENCY_TREE',title:'Phân tích ngược',content:'Cần chứng minh: AHCK là hình bình hành.',geometryImageData:geo.screens[5].imageData,sceneId:'tree',analysisSteps:['AHCK là hình bình hành','AH ∥ CK + AH = CK','AH ⟂ BD + CK ⟂ BD','△AHD ≅ △CKB']}]
];
async function fixture(index,st={}){const [name,subject,s]=fixtures[index];const l={id:'fixture-'+name,subject,title:'Ca kiểm thử trình bày',screens:[s]};await tv.evaluate(({l,st})=>{localStorage.setItem('lesson:'+l.id,JSON.stringify(l));applyState({type:'state',lessonId:l.id,lessonActivation:l.id,stateVersion:100,index:0,total:1,lesson:l,answerMode:st.steps?'steps':'hidden',answerStep:st.steps||0,analysisStep:st.analysis||0,showHint:false,board:{overlayScope:'overlay:fixture',whiteScope:'white:fixture',open:false},viewMode:l.screens[0].imageData||l.screens[0].geometryImageData?'split':'text',classroom:{}})},{l,st});await settled();return snapshot();}
for(let i=0;i<fixtures.length;i++){await fixture(i,{steps:2,analysis:3});await shot(fixtures[i][0],'Presentation fixture; not a real package');}
const responsive=[['TIN_MCQ',null],['ALG_EQUATION',3],['ALG_WORD_PROBLEM',5],['GEO_PROOF',null],['GEO_ANALYSIS',null]];
for(const [w,h] of [[1920,1080],[1600,900],[1366,768],[1280,720]]){
 await tv.setViewportSize({width:w,height:h});
 for(const [name,index] of responsive){if(index!=null)await fixture(index,{steps:2});else if(name==='TIN_MCQ'){await loadPackage('RC3_PED1_TEST_PACKAGES/TIN6_W04_LIVE_RC3_PED1.zip');await go(14)}else{await loadPackage('WEB_LIVE/HINH_HOC_8_T04_T07_DUAL_VISUAL_TEST.zip');await go(name==='GEO_PROOF'?8:7,name==='GEO_PROOF'?{steps:2}:{analysis:2})}await shot(name+'_'+w+'x'+h,index==null?'Real package':'Presentation fixture');}
}
// Conservative routing, parser safety, literal text and progressive disclosure.
await tv.setViewportSize({width:1366,height:768});await fixture(3,{steps:1});assert.equal((await snapshot()).steps,1);assert(!((await snapshot()).answer.includes('x = 7')));results.assertions.push('Algebra future steps absent from DOM');
await fixture(10,{analysis:2});assert(!((await snapshot()).analysis.includes('△AHD')));assert.equal(await tv.locator('.tvDependencyBranches').count(),1);results.assertions.push('Tree branching and future-node disclosure');
assert(await tv.evaluate(()=>resolveSubjectLayout({subjectMode:'GENERIC',geometryImage:'x'},{subject:'Hình học'})==='GENERIC'));assert(await tv.evaluate(()=>resolveSubjectLayout({content:'x = 2'},{subject:'Toán 8'})==='GENERIC'));assert(await tv.evaluate(()=>TVMultiEngine.options('A. One\nC. Three')===null));results.assertions.push('Router explicit priority and ambiguous generic; malformed MCQ fallback');
await tv.evaluate(()=>{const l={id:'atomic',subject:'Đại số 8',screens:[{type:'EQUATION',content:'2x + 3 = 7'}]};localStorage.setItem('lesson:atomic',JSON.stringify(l));applyState({type:'state',lessonId:'atomic',lessonActivation:'atomic',stateVersion:1,index:0,total:1,lesson:l,board:{overlayScope:'overlay:fixture',whiteScope:'white:fixture',open:false},viewMode:'text',answerMode:'hidden',classroom:{}})});await settled();assert.equal(await tv.locator('#content .tvAtomicExpression').innerText(),'2x + 3 = 7');results.assertions.push('Whole equation atomic');
// Offline reload with an already imported package; all web dependencies are local.
await loadPackage('RC3_PED1_TEST_PACKAGES/TIN8_W04_LIVE_RC3_PED1.zip');await go(3);await ctx.setOffline(true);await teacher.evaluate(()=>next());await settled();assert.equal((await snapshot()).mode,'COMPUTER_SCIENCE');await ctx.setOffline(false);results.assertions.push('Offline Teacher→TV navigation after local asset load');
fs.writeFileSync(out+'/results.json',JSON.stringify(results,null,2));await browser.close();console.log(JSON.stringify({realScreens:results.real.reduce((n,x)=>n+x.screens,0),screenshots:results.visual.length,errors,external,overflow:results.visual.filter(x=>x.overflow||x.horizontal).map(x=>x.name),realOverflow:results.real.map(x=>({package:x.package,overflow:x.states.filter(s=>s.overflow||s.horizontal)})),assertions:results.assertions},null,2));assert.equal(errors.length,0);assert.equal(external.length,0);
})().catch(e=>{console.error(e);process.exit(1)});
