const {chromium}=require('playwright'),fs=require('fs'),assert=require('assert/strict');
const out=__dirname,root='/workspace/phase9-subject-loader/packaged-smoke/WEB_LIVE_SUBJECT_LOADER_PHASE9_CANDIDATE',base='http://127.0.0.1:8784';
const result={mode:'AUDIT_ONLY',result:'RUNNING',observations:[],flows:[],layouts:[],errors:[],external:[],captures:[],windowsPhysical:'UNRUN',physicalTV:'UNRUN'};let b;
(async()=>{
 b=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});result.browser=b.version();const c=await b.newContext({viewport:{width:1366,height:768}});
 c.on('page',p=>{p.on('pageerror',e=>result.errors.push(e.message));p.on('request',r=>{if(!r.url().startsWith(base)&&!r.url().startsWith('data:'))result.external.push(r.url());});});
 const t=await c.newPage();await t.goto(base+'/WEB_LIVE/teacher.html');
 const observe=(name,evidence)=>result.observations.push({name,evidence});
 async function shot(name){await t.screenshot({path:out+'/'+name,animations:'disabled'});result.captures.push(name);}
 async function ready(){await t.waitForFunction(()=>!document.getElementById('subjectLoadBtn').disabled);}
 async function pick(path,kind='json'){
  const pending=t.waitForEvent('filechooser');await t.getByRole('button',{name:kind==='zip'?'📦 NHẬP LIVE.ZIP':'📄 NHẬP LESSON.JSON',exact:true}).click();const picker=await pending;const start=Date.now();await picker.setFiles(path);await ready();return Date.now()-start;
 }
 async function load(){await t.locator('#subjectLoadBtn').click();await t.waitForFunction(()=>document.getElementById('importer').style.display==='none');}
 const options=await t.locator('#lessonSubject option').allTextContents();assert.deepEqual(options.slice(1),['HÌNH HỌC','ĐẠI SỐ','TIN HỌC','BÀI CŨ / LEGACY']);observe('Four subject choices visible in native dropdown; startup has no remembered preference',{options,initialSelection:await t.locator('#lessonSubject').inputValue()});
 const algebra=root+'/ALGEBRA_PHASE5_TEST_PACKAGES/ALGEBRA_PROFILE_REPRESENTATIVE_TEST.json',informatics=root+'/INFORMATICS_PHASE6_TEST_PACKAGES/INFORMATICS_PROFILE_REPRESENTATIVE_TEST.json';
 await t.locator('#lessonSubject').selectOption('algebra');const initialMs=await pick(algebra);await shot('PREVIEW_ALGEBRA_MISSING_FIELDS.png');observe('Sparse synthetic Algebra preview',{fields:await t.locator('#subjectPreview dt').allTextContents(),validationReadyMs:initialMs});await load();
 const popup=t.waitForEvent('popup');await t.getByRole('button',{name:'📺 MỞ TV',exact:true}).click();const tv=await popup;await tv.waitForLoadState();await tv.waitForFunction(()=>lastState?.lessonActivation);await t.evaluate(()=>{go(2);revealStep();render();sync()});await tv.waitForFunction(()=>lastState?.index===2&&lastState.answerStep===1);
 const old=await tv.evaluate(()=>({activation:lastState.lessonActivation,index:lastState.index,answerStep:lastState.answerStep,profile:WebLiveProfiles.getContext().profileId,body:document.getElementById('screen').textContent}));
 observe('Loader entry is inside a collapsed System details group after startup/load',{systemInitiallyOpen:await t.locator('#systemGroup').evaluate(e=>e.open),libraryButtonVisible:await t.locator('button[onclick="showImporter()"]').isVisible()});await t.locator('#systemGroup > summary').click();await t.getByRole('button',{name:'📚 THƯ VIỆN / NHẬP BÀI',exact:true}).click();assert.equal(await t.locator('#lessonSubject').inputValue(),'algebra');observe('Selected subject already survives modal close/open in the same page',{selection:'algebra',activeIndicator:await t.locator('#subjectIndicator').textContent()});
 await t.locator('#lessonSubject').selectOption('informatics');const infoMs=await pick(informatics);const staged=await tv.evaluate(()=>({activation:lastState.lessonActivation,index:lastState.index,answerStep:lastState.answerStep,profile:WebLiveProfiles.getContext().profileId,body:document.getElementById('screen').textContent}));assert.deepEqual(staged,old);
 observe('Pending subject/package preview stays Teacher-only; TV retains current disclosed lesson',{old,unchanged:true,activeIndicatorBeforeCommit:await t.locator('#subjectIndicator').textContent(),stagedSubject:'informatics'});await load();await tv.waitForFunction(()=>WebLiveProfiles.getContext().profileId==='informatics');
 result.flows.push({scenario:'Teaching: new file, different subject',observedAutomationActions:4,modeledAppMouseClicks:5,modeledPickerClicks:2,modeledTotalClicks:7,decisionCount:3,applicationModalCount:1,nativePickerCount:1,fileBrowserSteps:'select file + Open, plus navigation if needed',validationReadyMs:infoMs,note:'selectOption = one automation action but normally dropdown-open + option-select = two mouse clicks. Native Windows picker, navigation and human reading time were not exercised.'});
 await t.getByRole('button',{name:'📚 THƯ VIỆN / NHẬP BÀI',exact:true}).click();await t.locator('#lessonSubject').selectOption('algebra');await t.locator('#library button').filter({hasText:'CHỌN BÀI'}).first().click();await ready();const savedBefore=await t.evaluate(()=>lessonActivation);await t.locator('#closeBtn').click();assert.equal(await t.evaluate(()=>lessonActivation),savedBefore);
 await t.getByRole('button',{name:'📚 THƯ VIỆN / NHẬP BÀI',exact:true}).click();observe('Canceled subject selection persists independently of actual active profile',{selected:await t.locator('#lessonSubject').inputValue(),activeIndicator:await t.locator('#subjectIndicator').textContent(),oldLessonStillActive:await t.evaluate(()=>lesson.subject_engine)});
 await t.locator('#library button').filter({hasText:'CHỌN BÀI'}).first().click();await ready();await load();
 const lib=await t.evaluate(()=>getLibrary());observe('Saved list is filtered by actual engine; open does update savedAt but does not move existing library entry',{selected:'algebra',libraryOrder:lib.map(x=>({id:x.id,savedAt:x.savedAt})),visibleLibraryTitle:'Algebra Phase5 — TEST ONLY / NOT SGK'});
 result.flows.push({scenario:'Teaching: saved lesson, same currently selected subject',modeledAppMouseClicks:3,modeledTotalClicks:3,decisionCount:2,applicationModalCount:1,nativePickerCount:0,fileBrowserSteps:0});
 result.flows.push({scenario:'Teaching: saved lesson, different subject',modeledAppMouseClicks:5,modeledTotalClicks:5,decisionCount:3,applicationModalCount:1,nativePickerCount:0,fileBrowserSteps:0});
 result.flows.push({scenario:'Teaching: new file, same selected subject',modeledAppMouseClicks:3,modeledPickerClicks:2,modeledTotalClicks:5,decisionCount:2,applicationModalCount:1,nativePickerCount:1,fileBrowserSteps:'select file + Open, plus navigation if needed'});
 // Existing bundled Legacy lessons intentionally lack subject_engine despite named subject.
 await t.getByRole('button',{name:'📚 THƯ VIỆN / NHẬP BÀI',exact:true}).click();await t.locator('#lessonSubject').selectOption('informatics');const pickerWait=t.waitForEvent('filechooser');await t.getByRole('button',{name:'📦 NHẬP LIVE.ZIP',exact:true}).click();await (await pickerWait).setFiles(root+'/RC3_PED1_TEST_PACKAGES/TIN6_W04_LIVE_RC3_PED1.zip');await t.waitForFunction(()=>document.getElementById('error').textContent.includes('Gói bài không khớp'));observe('Old Tin6 package has subject Tin học6 but Legacy engine fallback; mismatch is safe yet needs teacher interpretation',{preview:await t.locator('#subjectPreview').textContent(),warning:await t.locator('#error').textContent(),loadDisabled:await t.locator('#subjectLoadBtn').isDisabled()});await shot('LEGACY_METADATA_MISMATCH.png');
 await t.locator('#lessonSubject').selectOption('legacy');await ready();await load();
 for(const relative of ['WEB_LIVE/HINH_HOC_8_T04_T07_LIVE_TEST.zip','WEB_LIVE/HINH_HOC_8_T04_T07_DUAL_VISUAL_TEST.zip']){await t.getByRole('button',{name:'📚 THƯ VIỆN / NHẬP BÀI',exact:true}).click();await pick(root+'/'+relative,'zip');await load();}
 await t.getByRole('button',{name:'📚 THƯ VIỆN / NHẬP BÀI',exact:true}).click();const titles=await t.locator('#library .item b').allTextContents();observe('Saved library rows expose title only; two real bundled variants share the same visible title',{titles,duplicateTitles:titles.filter((x,n)=>titles.indexOf(x)!==n)});await shot('LIBRARY_DUPLICATE_TITLES.png');
 await t.locator('#lessonSubject').selectOption('geometry');const geometryMs=await pick('/workspace/g4-f01-fixture-revalidation/HINH8_VD2_GEOMETRY_PROFILE_TEST_G4F01_PATCHED.zip','zip');observe('Complete existing Geometry metadata preview',{fields:await t.locator('#subjectPreview dt').allTextContents(),validationReadyMs:geometryMs});
 for(const size of [{width:1920,height:1080},{width:1366,height:768},{width:1280,height:720}]){
  await t.setViewportSize(size);await t.locator('.importbox').evaluate(el=>el.scrollTop=0);
  const geometry=await t.evaluate(()=>{const panel=document.querySelector('.importbox');const box=panel.getBoundingClientRect();const metric=id=>{const e=document.getElementById(id),r=e.getBoundingClientRect();return {top:r.top,bottom:r.bottom,insidePanel:r.top>=box.top&&r.bottom<=box.bottom}};return {panel:{top:box.top,bottom:box.bottom,clientHeight:panel.clientHeight,scrollHeight:panel.scrollHeight},subject:metric('lessonSubject'),load:metric('subjectLoadBtn'),library:metric('library')};});result.layouts.push({...size,...geometry});await shot('GEOMETRY_PREVIEW_'+size.width+'.png');
 }
 await t.setViewportSize({width:1366,height:768});const beforeFinal=await t.evaluate(()=>({activation:lessonActivation,profile:WebLiveProfiles.getContext().profileId,storageCharacters:Object.keys(localStorage).reduce((n,k)=>n+k.length+localStorage.getItem(k).length,0)}));await t.locator('#subjectLoadBtn').click();await t.waitForFunction(()=>document.getElementById('importer').style.display==='none'||document.getElementById('error').textContent.startsWith('Không nạp được bài'));const finalCommit=await t.evaluate(()=>({modalOpen:document.getElementById('importer').style.display!=='none',warning:document.getElementById('error').textContent,activation:lessonActivation,profile:WebLiveProfiles.getContext().profileId,storageCharacters:Object.keys(localStorage).reduce((n,k)=>n+k.length+localStorage.getItem(k).length,0)}));observe('Final Geometry commit after accumulating image-heavy fixture packages',{beforeFinal,finalCommit,currentLessonPreserved:beforeFinal.activation===finalCommit.activation});if(finalCommit.modalOpen)await shot('LIBRARY_STORAGE_LOAD_FAILURE.png');const fresh=await c.newPage();await fresh.goto(base+'/WEB_LIVE/teacher.html');observe('New page/reload has saved lessons but does not restore subject preference',{selection:await fresh.locator('#lessonSubject').inputValue(),storedLibraryCount:await fresh.evaluate(()=>getLibrary().length)});assert.equal(await fresh.locator('#lessonSubject').inputValue(),'');
 // Follow up only the observed storage limit, without editing packages or app.
 if(finalCommit.modalOpen){
  await t.locator('#lessonSubject').selectOption('legacy');await t.locator('#lessonSubject').selectOption('geometry');await ready();await t.locator('#subjectLoadBtn').click();await t.waitForFunction(()=>document.getElementById('error').textContent.startsWith('Không nạp được bài'));
  observe('Repeated Geometry commit in the same full library',{warning:await t.locator('#error').textContent(),sameActivation:await t.evaluate(expected=>lessonActivation===expected,beforeFinal.activation)});
 }
 const clean=await b.newContext({viewport:{width:1366,height:768}}),single=await clean.newPage();await single.goto(base+'/WEB_LIVE/teacher.html');await single.locator('#lessonSubject').selectOption('geometry');await single.locator('#zipfile').setInputFiles('/workspace/g4-f01-fixture-revalidation/HINH8_VD2_GEOMETRY_PROFILE_TEST_G4F01_PATCHED.zip');await single.waitForFunction(()=>!document.getElementById('subjectLoadBtn').disabled);await single.locator('#subjectLoadBtn').click();await single.waitForFunction(()=>document.getElementById('importer').style.display==='none');observe('Same Geometry package succeeds in a fresh isolated storage context',{profile:await single.evaluate(()=>WebLiveProfiles.getContext().profileId),savedCount:await single.evaluate(()=>getLibrary().length),storageCharacters:await single.evaluate(()=>Object.keys(localStorage).reduce((n,k)=>n+k.length+localStorage.getItem(k).length,0)),testOnly:true});await clean.close();
 assert.deepEqual(result.errors,[]);assert.deepEqual(result.external,[]);result.result='COMPLETE';result.usabilityVerdict='USABLE_WITH_FRICTION_AND_STORAGE_LIMIT_CLOUD_AUDIT';fs.writeFileSync(out+'/RUNTIME_AUDIT.json',JSON.stringify(result,null,2)+'\n');await b.close();console.log(JSON.stringify({result:'COMPLETE',observations:result.observations.length,flows:result.flows.length,layouts:result.layouts.length,physical:'UNRUN'}));
})().catch(async e=>{result.result='AUDIT_HARNESS_FAILED';result.error={message:e.message,stack:e.stack};fs.writeFileSync(out+'/RUNTIME_AUDIT.json',JSON.stringify(result,null,2)+'\n');await b?.close();console.error(e);process.exitCode=1;});
