const {chromium}=require('playwright'),fs=require('fs'),assert=require('assert/strict'),path=require('path');
const out=process.env.P12_LIBRARY_OUT||__dirname,root=process.env.P12_ROOT||__dirname+'/working/WEB_LIVE_LESSON_LIBRARY_PHASE12_WORKING_COPY',base=process.env.P12_BASE||'http://127.0.0.1:8787';fs.mkdirSync(out,{recursive:true});
const fixture=JSON.parse(fs.readFileSync('/workspace/p12-1-legacy-subject/SYNTHETIC_LARGE_LIBRARY.json')),result={result:'RUNNING',checks:[],errors:[],external:[],captures:[],performance:[],interactions:[],syntheticOnly:true,windowsPhysical:'UNRUN',physicalTV:'UNRUN',realClassroom:'UNRUN'};let browser;
const key='webLiveSubjectLoaderQuickAccessPhase11',controls={grade:'#lessonGrade',week:'#lessonWeek',period:'#lessonPeriod'};
const check=(name,evidence={})=>{result.checks.push({name,result:'PASS',evidence});console.log(name)};
(async()=>{
 browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});result.browser=browser.version();
 async function context(){const c=await browser.newContext({viewport:{width:1366,height:768}});c.on('page',p=>{p.on('pageerror',e=>result.errors.push(e.message));p.on('request',r=>{if(!r.url().startsWith(base)&&!r.url().startsWith('data:'))result.external.push(r.url())})});return c}
 async function page(c){const t=await c.newPage();await t.goto(base+'/WEB_LIVE/teacher.html');return t}
 async function seed(t,lessons){await t.evaluate(lessons=>{const lib=[];for(const source of lessons){const x={...source,_runtimeSourceKey:'json:P12-synthetic:'+source.id};localStorage.setItem('lesson:'+x.id,JSON.stringify(x));lib.unshift({id:x.id,title:x.title,subject:x.subject,week:x.week??'',period:x.period??'',savedAt:new Date(0).toISOString()})}localStorage.setItem('webLiveLibrary',JSON.stringify(lib));},lessons);await t.evaluate(async()=>{await WebLiveSubjectStorage.refresh();renderLibrary();})}
 const optionData=(t,key)=>t.locator(controls[key]+' option').evaluateAll(nodes=>nodes.map(n=>({value:n.value,text:n.textContent})));
 const numbered=async(t,key)=>(await optionData(t,key)).filter(x=>x.value.startsWith('n:')).map(x=>Number(x.value.slice(2)));
 const ids=t=>t.locator('#library .libraryLesson').evaluateAll(nodes=>nodes.map(n=>n.dataset.lessonId));
 const row=(t,id)=>t.locator('#library .libraryLesson').filter({has:t.locator('b')}).locator('button').filter({hasText:'CHỌN BÀI'}); // Direct by metadata identity below.
 const chooseRow=(t,id)=>t.locator('#library .libraryLesson').filter({hasText:''}).locator('button').filter({hasText:'CHỌN BÀI'});
 const selectedRow=(t,id)=>t.locator('#library .libraryLesson').filter({has:t.locator('b')}).evaluateAll((nodes,id)=>nodes.find(n=>n.dataset.lessonId===id)?.textContent,id);
 async function choose(t,subject){await t.evaluate(()=>showImporter());await t.locator('#lessonSubject').selectOption(subject)}
 async function pick(t,id){await t.locator('#library .libraryLesson').evaluateAll((nodes,id)=>{const target=nodes.find(n=>n.dataset.lessonId===id);if(!target)throw Error('Missing row '+id);target.querySelector('button').click()},id);await t.waitForFunction(()=>!document.getElementById('subjectLoadBtn').disabled)}
 async function load(t){await t.locator('#subjectLoadBtn').click();await t.waitForFunction(()=>document.getElementById('importer').style.display==='none')}
 const snapshot=t=>t.evaluate(k=>({lesson:JSON.stringify(lesson),activation:lessonActivation,index:i,answerMode,answerStep,analysisStep,showHint,zoom,focus:classroomController.focus,quick:localStorage.getItem(k),storage:Object.fromEntries(Object.keys(localStorage).sort().filter(k=>!['webLiveStateV042','WEB_LIVE_TTS_PRESENTATION_V1','WEB_LIVE_TTS_REGISTRY_V1'].includes(k)).map(k=>[k,localStorage.getItem(k)]))}),key);
 async function shot(t,name){await t.screenshot({path:path.join(out,name),animations:'disabled'});result.captures.push(name)}
 const c=await context(),t=await page(c);assert(await t.locator('#lessonGrade').isDisabled());assert(await t.locator('#lessonWeek').isDisabled());assert(await t.locator('#lessonPeriod').isDisabled());for(const key of Object.keys(controls))assert.equal((await optionData(t,key)).length,1);check('EMPTY_LIBRARY_NO_PHANTOM_CHOICES');
 await seed(t,fixture.lessons);const start=Date.now();await choose(t,'algebra');result.performance.push({operation:'select subject / render large library',elapsedMs:Date.now()-start,libraryCount:fixture.lessons.length});assert.equal((await ids(t)).length,165);assert.equal(await t.locator('#libraryIncomplete .libraryLesson').count(),5);assert.deepEqual(await numbered(t,'grade'),[6,7,8,9]);assert.deepEqual(await numbered(t,'week'),[1,2,5,10,11]);assert.deepEqual(await numbered(t,'period'),[1,2,9,10]);check('GRADE_SORT');check('WEEK_NUMERIC_SORT');check('PERIOD_NUMERIC_SORT');
 for(const profile of fixture.profiles){await choose(t,profile);const actual=await ids(t);assert.equal(actual.length,165);assert(actual.every(id=>id.startsWith('P12_'+profile+'_')))}check('SUBJECT_FILTER_FOUR_METADATA_GROUPS',{each:165,total:660,legacyAbsentEngine:true});
 await choose(t,'algebra');await t.locator(controls.grade).selectOption('n:8');assert.deepEqual(await numbered(t,'week'),[1,2,5,10,11]);await t.locator(controls.week).selectOption('n:5');assert.deepEqual(await numbered(t,'period'),[1,2,9,10]);await t.locator(controls.period).selectOption('n:9');let actual=await ids(t);assert.equal(actual.length,7);assert.equal(await t.locator('#libraryIncomplete .libraryLesson').count(),5);assert(actual.includes('P12_algebra_G8_W5_P9_01'));assert(actual.includes('P12_algebra_G8_W5_P9_02'));check('GRADE_WEEK_PERIOD_NARROWING',{complete:2,incomplete:5});
 for(const profile of fixture.profiles){await choose(t,profile);await t.locator(controls.grade).selectOption('n:8');await t.locator(controls.week).selectOption('n:5');await t.locator(controls.period).selectOption('n:9');const missing=await t.locator('#libraryIncomplete .libraryLesson').evaluateAll(nodes=>nodes.map(n=>({id:n.dataset.lessonId,text:n.textContent})));assert.equal(missing.length,5);for(const value of missing){assert(value.text.includes('Chưa đủ thông tin'));if(value.id.endsWith('MISSING_ALL'))assert(!/LỚP \d|TUẦN \d|TIẾT \d/u.test(value.text))}assert(!(await optionData(t,'grade')).some(x=>x.text==='LỚP 8A'))}check('MISSING_METADATA_VISIBLE_NO_FALSE_FIELDS',{profiles:4,missingPerProfile:5,classNotInferredAsGrade:true});
 await choose(t,'algebra');await t.locator(controls.grade).selectOption('missing');assert.equal((await ids(t)).length,3);assert.deepEqual(await numbered(t,'week'),[5]);await t.locator(controls.week).selectOption('missing');assert.equal((await ids(t)).length,1);assert.equal((await ids(t))[0],'P12_algebra_MISSING_ALL');check('UNKNOWN_BUCKET_NARROWS_ONLY_ACTUAL_MISSING_FIELDS');
 await choose(t,'algebra');await t.locator(controls.grade).selectOption('n:6');await t.locator(controls.week).selectOption('n:10');await t.locator(controls.period).selectOption('n:10');assert.deepEqual(await numbered(t,'week'),[1,2,5,10,11]); // Unknown-grade rows may contribute only actual values.
 await t.locator(controls.grade).selectOption('n:9');assert.equal(await t.locator(controls.week).inputValue(),'');assert.equal(await t.locator(controls.period).inputValue(),'');await t.locator(controls.week).selectOption('n:2');await t.locator(controls.period).selectOption('n:10');await t.locator(controls.week).selectOption('n:11');assert.equal(await t.locator(controls.period).inputValue(),'');check('UPSTREAM_CHANGE_RESETS_DESCENDANTS');
 await t.locator(controls.grade).selectOption('n:8');await t.locator(controls.week).selectOption('n:5');await t.locator(controls.period).selectOption('n:9');const stable=await ids(t);await t.evaluate(()=>{const lib=getLibrary();localStorage.setItem('webLiveLibrary',JSON.stringify(lib.reverse()));renderLibrary()});assert.deepEqual(await ids(t),stable);const twin=t.locator('#library > .libraryLesson');assert.equal(await twin.count(),2);assert.equal(await twin.locator('.libraryReference').count(),2);assert((await twin.nth(0).textContent()).includes('P12_algebra_G8_W5_P9_01'));assert((await twin.nth(1).textContent()).includes('P12_algebra_G8_W5_P9_02'));check('LESSON_LIST_STABILITY_AND_DUPLICATE_TITLE_IDENTIFICATION');
 // Catalog/content/class hints cannot override actual lesson metadata.
 await t.evaluate(async()=>{const lib=getLibrary(),entry=lib.find(x=>x.id==='P12_algebra_G6_W1_P1_01');entry.grade=9;entry.week=99;entry.period=88;entry.title='HINH_HOC_9_T99_T88.zip';localStorage.setItem('webLiveLibrary',JSON.stringify(lib));const x=await WebLiveSubjectStorage.readLesson(entry.id);x.grade='6';x.week='1';x.period='1';x.subject_engine=' AlGeBrA ';localStorage.setItem('lesson:'+entry.id,JSON.stringify(x));await WebLiveSubjectStorage.refresh();renderLibrary()});await choose(t,'algebra');assert(!(await numbered(t,'week')).includes(99));assert(!(await numbered(t,'period')).includes(88));await t.locator(controls.grade).selectOption('n:6');await t.locator(controls.week).selectOption('n:1');await t.locator(controls.period).selectOption('n:1');assert((await ids(t)).includes('P12_algebra_G6_W1_P1_01'));assert((await selectedRow(t,'P12_algebra_G6_W1_P1_01')).includes('LỚP 6'));assert(!(await selectedRow(t,'P12_algebra_G6_W1_P1_01')).includes('T99'));check('METADATA_SOURCE_OF_TRUTH_NO_CONTENT_FILENAME_HEURISTICS');
 // Warm a real native current lesson, then change every filter while TV is disclosed.
 await choose(t,'legacy');await pick(t,'P12_legacy_G8_W5_P9_01');await load(t);const pop=t.waitForEvent('popup');await t.getByRole('button',{name:'📺 MỞ TV',exact:true}).click();const tv=await pop;await tv.waitForLoadState();await t.evaluate(()=>{revealStep();zoomBy(.4);classroomController.focus={region:'answer',index:0};render();sync()});await tv.waitForFunction(()=>lastState?.answerStep===1);await t.evaluate(()=>showImporter());const before=await snapshot(t),tvBefore=await tv.evaluate(()=>({activation:lastState.lessonActivation,index:lastState.index,answerStep:lastState.answerStep,body:document.getElementById('screen').textContent}));await t.locator(controls.grade).selectOption('n:8');await t.locator(controls.week).selectOption('n:5');await t.locator(controls.period).selectOption('n:9');await t.locator('#lessonSubject').selectOption('algebra');for(const selector of Object.values(controls))assert.equal(await t.locator(selector).inputValue(),'');assert.deepEqual(await snapshot(t),before);assert.deepEqual(await tv.evaluate(()=>({activation:lastState.lessonActivation,index:lastState.index,answerStep:lastState.answerStep,body:document.getElementById('screen').textContent})),tvBefore);check('SUBJECT_CHANGE_RESETS_FILTERS_PRESERVES_CURRENT_TEACHER_TV');
 await t.evaluate(()=>{window.p12Writes=[];window.p12Set=Storage.prototype.setItem;window.p12Remove=Storage.prototype.removeItem;Storage.prototype.setItem=function(k,v){window.p12Writes.push({op:'set',key:k,characters:v.length});return window.p12Set.call(this,k,v)};Storage.prototype.removeItem=function(k){window.p12Writes.push({op:'remove',key:k});return window.p12Remove.call(this,k)}});await t.locator(controls.grade).selectOption('n:8');await t.locator(controls.week).selectOption('n:5');await t.locator(controls.period).selectOption('n:9');const writes=await t.evaluate(()=>window.p12Writes);await t.evaluate(()=>{Storage.prototype.setItem=window.p12Set;Storage.prototype.removeItem=window.p12Remove});assert.deepEqual(writes,[]);assert.deepEqual(await snapshot(t),before);check('FILTER_METADATA_STORAGE_ZERO_WRITES_NO_PACKAGE_DUPLICATION',{writes:0,persistentIndexKeys:0,inMemoryStateValues:3});
 await pick(t,'P12_algebra_G8_W5_P9_01');assert(await t.locator('#subjectLoadBtn').isEnabled());await t.locator(controls.grade).selectOption('n:6');assert(await t.locator('#subjectLoadBtn').isDisabled());assert(await t.locator('#subjectPreview').isHidden());assert.deepEqual(await snapshot(t),before);check('FILTER_CHANGE_INVALIDATES_PENDING_CHOICE_NOT_CURRENT_LESSON');
 // Missing/disappearing reference cannot accidentally commit a previous staged lesson.
 await choose(t,'algebra');await pick(t,'P12_algebra_G8_W5_P9_01');await t.evaluate(()=>openSaved('DOES_NOT_EXIST_P12'));assert(await t.locator('#subjectLoadBtn').isDisabled());assert((await t.locator('#error').textContent()).includes('Không tìm thấy'));assert.deepEqual(await snapshot(t),before);check('MISSING_REFERENCE_CLEARS_STALE_PENDING_LOAD');
 await choose(t,'legacy');await t.locator(controls.grade).selectOption('n:6');await t.locator(controls.week).selectOption('n:1');await t.locator(controls.period).selectOption('n:1');await t.locator('#recentLessons button').first().click();await t.waitForFunction(()=>!document.getElementById('subjectLoadBtn').disabled);for(const selector of Object.values(controls))assert.equal(await t.locator(selector).inputValue(),'');assert.deepEqual(await snapshot(t),before);await load(t);assert.equal(await t.evaluate(()=>currentLessonId),'P12_legacy_G8_W5_P9_01');assert.equal(await tv.evaluate(()=>lastState.answerMode),'hidden');assert.equal(await tv.evaluate(()=>lastState.zoom),1);check('RECENT_OUTSIDE_FILTERS_REUSES_STAGE_VALIDATION_AND_NATIVE_RESET');
 // Actual app actions for common library access; no native Windows mouse claim.
 assert.equal(await t.locator('#systemGroup').evaluate(e=>e.open),false);const actions=[];await t.locator('#systemGroup > summary').click();actions.push('open System group');await t.getByRole('button',{name:'📚 THƯ VIỆN / NHẬP BÀI',exact:true}).click();actions.push('open existing Loader');await t.locator(controls.grade).selectOption('n:8');actions.push('choose Grade8');const commonId='P12_legacy_G8_W1_P1_01';const first=t.locator('#library > .libraryLesson').first();assert.equal(await first.getAttribute('data-lesson-id'),commonId);assert(await first.isVisible());assert(await first.evaluate(e=>{const r=e.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight}));await first.getByRole('button',{name:'CHỌN BÀI',exact:true}).click();actions.push('choose lesson');await t.waitForFunction(()=>!document.getElementById('subjectLoadBtn').disabled);assert(await t.locator('#subjectLoadBtn').evaluate(e=>{const r=e.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight}));await load(t);actions.push('explicit validated LOAD');assert.equal(await t.evaluate(()=>currentLessonId),commonId);result.interactions.push({scenario:'Common saved-library load, remembered current subject, System initially collapsed, one grade filter',meaningfulInteractions:actions.length,observedAutomationActions:actions,modeledMouseClicks:6,fileBrowserSteps:0,modalCount:1,windowsPhysical:'UNRUN',qualification:'Native dropdown selectOption models one meaningful selection but normally two mouse clicks. No manual navigation/scroll needed for this fixture first row; arbitrary row search/reading not timed.'});assert.equal(actions.length,5);check('COMMON_LIBRARY_LOAD_WITHIN_FIVE_MEANINGFUL_INTERACTIONS',result.interactions[0]);
 await t.getByRole('button',{name:'📚 THƯ VIỆN / NHẬP BÀI',exact:true}).click();await t.locator(controls.week).selectOption('n:5');await t.locator(controls.period).selectOption('n:9');for(const size of [{width:1920,height:1080},{width:1366,height:768},{width:1280,height:720}]){await t.setViewportSize(size);await shot(t,'LIBRARY_FILTERS_'+size.width+'.png');assert(await t.locator('#closeBtn').isVisible());}await t.setViewportSize({width:1366,height:768});await pick(t,'P12_legacy_G8_W5_P9_02');await shot(t,'LIBRARY_VALIDATED_PREVIEW.png');await t.locator('#closeBtn').click();await t.reload();assert.equal(await t.locator('#lessonSubject').inputValue(),'legacy');for(const selector of Object.values(controls))assert.equal(await t.locator(selector).inputValue(),'');assert.equal(await t.evaluate(()=>currentLessonId),commonId);assert.equal(await t.evaluate(()=>answerMode),'hidden');check('RELOAD_REMEMBERS_SUBJECT_RESETS_FILTERS_PRESERVES_NATIVE_ACCEPTED_SESSION_RESTORE');await c.close();
 const missingContext=await context(),mt=await page(missingContext);await mt.evaluate(k=>localStorage.setItem(k,JSON.stringify({version:1,lastSubject:'legacy',recent:[]})),key);await mt.reload();assert.equal(await mt.locator('#lessonSubject').inputValue(),'legacy');assert.equal(await mt.evaluate(()=>lesson),null);check('REMEMBERED_SUBJECT_WITHOUT_NATIVE_SESSION_DOES_NOT_AUTO_LOAD');const lone={...fixture.lessons.find(x=>x.id==='P12_legacy_MISSING_ALL'),title:'HINH_HOC_8_W05_TIET09.zip'};await seed(mt,[lone]);await choose(mt,'legacy');for(const name of Object.keys(controls)){const opts=await optionData(mt,name);assert.equal(opts.length,2);assert.equal(opts[1].value,'missing')}assert.equal(await mt.locator('#libraryIncomplete .libraryLesson').count(),1);await pick(mt,lone.id);assert.deepEqual(await mt.locator('#subjectPreview dt').allTextContents(),['Môn','Tên bài','Chế độ chạy']);await load(mt);assert.equal(await mt.evaluate(()=>WebLiveProfiles.getContext().profileId),'legacy');check('OLD_PACKAGE_ALL_FIELDS_MISSING_VISIBLE_LOADABLE_WITHOUT_FALSE_METADATA');await missingContext.close();
 assert.deepEqual(result.errors,[]);assert.deepEqual(result.external,[]);check('ZERO_RUNTIME_ERRORS_EXTERNAL_REQUESTS');result.result='PASS';fs.writeFileSync(out+'/LIBRARY_RESULTS.json',JSON.stringify(result,null,2)+'\n');await browser.close();console.log(JSON.stringify({result:'PASS',groups:result.checks.length,syntheticLessons:fixture.lessons.length}));
})().catch(async e=>{result.result='FAIL';result.error={message:e.message,stack:e.stack};fs.writeFileSync(out+'/LIBRARY_RESULTS.json',JSON.stringify(result,null,2)+'\n');await browser?.close();console.error(e);process.exitCode=1});
