const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),assert=require('assert/strict');
const out=__dirname,root=process.env.WEB_LIVE_ALGEBRA_ROOT||out+'/working/WEB_LIVE_ALGEBRA_PHASE5_WORKING_COPY',base=process.env.WEB_LIVE_ALGEBRA_BASE||'http://127.0.0.1:8776';
const result={result:'RUNNING',checks:[],errors:[],externalRequests:[],captures:[],fixture:'Synthetic interface fixture only; not SGK or classroom validation'};let browser;
const captures=path.join(out,'TARGETED_CAPTURES');fs.mkdirSync(captures,{recursive:true});
(async()=>{
 browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});result.browser=browser.version();
 const c=await browser.newContext({viewport:{width:1366,height:768}});c.on('page',p=>{p.on('pageerror',e=>result.errors.push(e.message));p.on('request',r=>{if(!r.url().startsWith(base)&&!r.url().startsWith('data:'))result.externalRequests.push(r.url())});});
 const t=await c.newPage();await t.goto(base+'/WEB_LIVE/teacher.html');await t.locator('#lessonSubject').selectOption('algebra');await t.locator('#jsonfile').setInputFiles(root+'/ALGEBRA_PHASE5_TEST_PACKAGES/ALGEBRA_PROFILE_REPRESENTATIVE_TEST.json');await t.waitForFunction(()=>!document.getElementById('subjectLoadBtn').disabled);await t.locator('#subjectLoadBtn').click();await t.waitForFunction(()=>lesson?.id==='ALGEBRA_PHASE5_REPRESENTATIVE_TEST');
 const initialMemory=await t.evaluate(()=>JSON.stringify(lesson));const pending=t.waitForEvent('popup');await t.getByRole('button',{name:'📺 MỞ TV',exact:true}).click();const tv=await pending;await tv.waitForLoadState();await tv.setViewportSize({width:1920,height:1080});
 async function settle(){const state=await t.evaluate(()=>({version:stateVersion,index:i,activation:lessonActivation}));await tv.waitForFunction(s=>lastState?.stateVersion>=s.version&&lastState.index===s.index&&lastState.lessonActivation===s.activation,state);await tv.waitForFunction(()=>document.getElementById('screen').dataset.algebraMathReady==='true');await tv.waitForFunction(()=>[...document.querySelectorAll('#answer,#answer .focusBlock')].every(n=>n.getAnimations().every(a=>a.playState!=='running')));await tv.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));}
 async function go(index){await t.locator('#jump').selectOption(String(index));await settle();}
 async function capture(name){const file=name+'.png';await tv.waitForFunction(()=>document.getAnimations().every(a=>a.playState!=='running'));await tv.evaluate(()=>document.fonts.ready);await tv.screenshot({path:path.join(captures,file),animations:'disabled'});result.captures.push(file);}
 async function snapshot(){await settle();return tv.evaluate(()=>({index:lastState.index,answerMode:lastState.answerMode,answerStep:lastState.answerStep,analysisStep:lastState.analysisStep,showHint:lastState.showHint,pedagogy:lastState.pedagogy,zoom:lastState.zoom,pan:lastState.pan,pointer:lastState.pointer,scene:lastState.sceneId,board:lastState.board,layout:lastState.classroom.layout,source:cachedLesson._runtimeSourceKey,focus:lastState.classroom.focus,profile:WebLiveAlgebra.getState(),proof:[...document.querySelectorAll('#answer .algebraProofStep')].map(n=>({index:Number(n.dataset.stepIndex),display:getComputedStyle(n).display,opacity:Number(getComputedStyle(n).opacity),state:n.dataset.stepState,disclosure:n.dataset.disclosure,focused:n.classList.contains('isFocused')})),overflow:document.querySelector('.textPane').scrollHeight>document.querySelector('.textPane').clientHeight+2,horizontal:document.querySelector('.textPane').scrollWidth>document.querySelector('.textPane').clientWidth+2}));}
 const check=(name,evidence={})=>result.checks.push({name,result:'PASS',evidence});
 await settle();assert.equal(await tv.evaluate(()=>MathJax.version),'3.2.2');assert(await tv.locator('mjx-container[jax="SVG"] svg').count()>0);assert(await tv.locator('[data-mml-node="msup"]').count()>0);assert(await tv.locator('[data-mml-node="msqrt"]').count()>0);check('MATHJAX_RENDERING + EXPRESSION_RENDERING: local SVG powers/root/polynomial');await capture('EXPRESSION_POWERS_ROOT');
 assert(!(await tv.locator('#screen').textContent()).includes('HINT_ONLY_A5_EXPR'));assert.equal(await tv.locator('#answer .algebraProofStep').count(),0);check('Hidden hint source and answer absent from TV DOM');
 await go(1);const fraction=await tv.locator('#content [data-mml-node="mfrac"]').first().evaluate(n=>{const rows=[...n.children].filter(c=>c.matches('g[data-mml-node]')).map(c=>c.getBoundingClientRect());return{children:rows.map(r=>({y:r.y,height:r.height})),bars:n.querySelectorAll('rect').length}});assert(fraction.children.length>=2);assert(fraction.children[0].y<fraction.children[1].y);assert(fraction.bars>0);check('FRACTION_RENDERING: numerator above denominator with visible bar',fraction);await capture('FRACTION_STACKED');
 await go(2);const initial=await snapshot();assert.equal(initial.answerStep,0);assert.equal(initial.proof.length,0);assert(initial.profile.stepStates.every(x=>x.disclosure==='UNREVEALED'));assert(!(await tv.locator('#screen').textContent()).includes('FUTURE_STEP_4_ONLY'));assert(!(await tv.locator('#screen').textContent()).includes('FINAL_CONCLUSION_ONLY'));
 await t.locator('#hintBtn').click();await settle();assert(await tv.locator('#hint').isVisible());assert((await tv.locator('#hint').textContent()).includes('HINT_ONLY_A5_TRANSFORM'));assert.equal(await tv.locator('#answer .algebraProofStep').count(),0);await t.locator('#hintBtn').click();await settle();assert(!(await tv.locator('#screen').textContent()).includes('HINT_ONLY_A5_TRANSFORM'));check('HINT_CONTROL: native toggle reveals/hides only hint, no answer');
 for(let n=1;n<=3;n++){await t.locator('button[onclick="revealStep()"]').click();const s=await snapshot();assert.equal(s.answerStep,n);assert.equal(s.proof.length,n);assert.equal(s.proof.at(-1).state,'CURRENT');assert(s.proof.slice(0,-1).every(x=>x.state==='COMPLETED'));assert(s.proof.every(x=>x.disclosure==='REVEALED'&&x.display!=='none'));assert(s.profile.stepStates.slice(n).every(x=>x.disclosure==='UNREVEALED'));assert(!(await tv.locator('#screen').textContent()).includes('FUTURE_STEP_4_ONLY'));assert(!(await tv.locator('#screen').textContent()).includes('FINAL_CONCLUSION_ONLY'));}
 const before=await snapshot();assert(before.proof[2].opacity===1&&before.proof[0].opacity<1);check('STEP_REVEAL + STEP_HIGHLIGHT: native 1→2→3, current/completed/disclosure states; future4 absent');
 await t.locator('#classroomGroup > summary').click();await t.locator('#displayToolsGroup > summary').click();await t.locator('#focusMode').click();await t.locator('#previewAnswer .focusBlock').nth(2).click();const focus=await snapshot();assert.equal(focus.focus.index,2);assert(focus.proof.every(x=>x.display!=='none'));assert(focus.proof[2].opacity===1&&focus.proof.slice(0,2).every(x=>x.opacity>0&&x.opacity<1));
 const invariant=s=>Object.fromEntries(['index','answerMode','answerStep','analysisStep','showHint','pedagogy','zoom','pan','pointer','scene','board','layout','source'].map(k=>[k,s[k]]));assert.deepEqual(invariant(focus),invariant(before));assert.deepEqual(focus.profile.stepStates.map(({focused,...s})=>s),before.profile.stepStates.map(({focused,...s})=>s));await capture('FOCUS_STEP3_PREVIOUS_VISIBLE');
 await t.locator('button[onclick="classroomController.clearFocus()"] ').click();await t.locator('#focusMode').click();const off=await snapshot();assert.equal(off.focus,null);assert.deepEqual(invariant(off),invariant(before));assert.deepEqual(off.proof,before.proof);check('ALGEBRA_FOCUS: previous visible/dim, current strong, exact clear restoration and preserved native state');
 await t.locator('#focusMode').click();await t.locator('#previewAnswer .focusBlock').nth(0).click();const earlier=await snapshot();assert(earlier.proof[0].focused&&earlier.proof[0].opacity===1);assert(earlier.proof.every(x=>x.display!=='none'));assert.deepEqual(invariant(earlier),invariant(before));await t.locator('button[onclick="classroomController.clearFocus()"] ').click();await t.locator('#focusMode').click();await settle();check('Earlier-step Focus changes emphasis only; native current step remains current');
 await t.locator('button[onclick="previousStep()"] ').click();const back=await snapshot();assert.equal(back.answerStep,2);assert.equal(back.proof.length,2);assert.equal(back.proof.at(-1).state,'CURRENT');await t.locator('button[onclick="hideAnswer()"] ').click();await settle();assert.equal(await tv.locator('#answer').textContent(),'');check('Previous Step/Hide Answer remove later proof and all concealed metadata');
 await t.locator('#ansBtn').click();const full=await snapshot();assert.equal(full.answerMode,'full');assert.equal(full.proof.length,4);assert(full.profile.stepStates.every(x=>x.progress==='COMPLETED'));assert((await tv.locator('#answer').textContent()).includes('FINAL_CONCLUSION_ONLY'));assert((await tv.locator('#answer').textContent()).includes('Quy tắc / Giải thích'));assert((await tv.locator('#answer').textContent()).includes('Biểu thức gốc'));assert((await tv.locator('#answer').textContent()).includes('Kết quả'));await t.locator('#ansBtn').click();await settle();assert.equal(await tv.locator('#answer').textContent(),'');check('ANSWER_CONTROL + authored original/transformation/reason/result: full only on native command');
 await go(3);assert(await tv.locator('#content svg [data-c="3D"]').count()>0);await t.locator('button[onclick="revealStep()"]').click();await settle();assert(await tv.locator('#answer svg').count()>0);check('EQUATION_RENDERING: native equation and disclosed transformation rendered SVG');await capture('EQUATION_STEP1');
 await go(4);assert(await tv.locator('#content svg [data-c="3C"]').count()>0);await t.locator('button[onclick="revealStep()"]').click();await settle();assert(await tv.locator('#answer svg [data-c="3E"]').count()>0);check('INEQUALITY_RENDERING: authored inequality direction and reason preserved');await capture('INEQUALITY');
 await go(5);const system=await tv.locator('#content [data-mml-node="mtable"]').first().evaluate(n=>({rows:[...n.querySelectorAll('[data-mml-node="mtr"]')].map(r=>({y:r.getBoundingClientRect().y,height:r.getBoundingClientRect().height})),equations:n.querySelectorAll('[data-c="3D"]').length}));assert.equal(system.rows.length,2);assert(system.rows[0].y<system.rows[1].y);assert.equal(system.equations,2);assert(await tv.locator('#content svg [data-c="7B"]').count()>0);check('SYSTEM_RENDERING: brace, two separate equation rows, not flattened',system);await capture('SYSTEM_TWO_ROWS');
 await go(6);assert.equal(await tv.locator('.algebraErrorComparison').count(),0);assert(!(await tv.locator('#screen').textContent()).includes('CORRECT_SOLUTION_ONLY'));await t.locator('button[onclick="revealStep()"]').click();await settle();assert.equal(await tv.locator('.algebraErrorComparison').count(),1);assert((await tv.locator('.algebraErrorComparison').textContent()).includes('CORRECT_SOLUTION_ONLY'));assert(await tv.locator('.algebraErrorComparison svg').count()>=3);check('ERROR_COMPARISON: authored student/correct/rule only after associated step reveal');await capture('ERROR_COMPARISON');
 await go(7);assert.equal(await tv.locator('.algebraErrorComparison').count(),0);check('No student error or correction invented on a lesson without error-comparison data');
 const stages=new Set();for(let index=0;index<10;index++){await go(index);stages.add((await snapshot()).profile.stage);for(const size of [{width:1920,height:1080},{width:1366,height:768},{width:1280,height:720}]){await tv.setViewportSize(size);await settle();const s=await snapshot();assert(!s.overflow,'Question overflow index'+index);assert(!s.horizontal,'Horizontal overflow index'+index);}}
 assert.deepEqual([...stages].sort(),['PROBLEM','OBSERVE','REMARK','TRANSFORM','EXPLAIN','CONCLUDE','PRACTICE','APPLY'].sort());check('All eight optional authored pedagogical stages; ten-screen questions fit three TV viewports');
 await go(9);const options=await tv.locator('.tvOptionCard').evaluateAll(ns=>ns.map(n=>{const r=n.getBoundingClientRect();return{x:r.x,y:r.y,width:r.width,right:r.right,overflow:n.scrollWidth>n.clientWidth+2}}));assert.equal(options.length,4);assert(options.every(x=>Math.abs(x.x-options[0].x)<1&&Math.abs(x.width-options[0].width)<1&&!x.overflow));assert(options.every((x,i)=>!i||x.y>options[i-1].y));assert.equal(await tv.locator('.tvOptionCard svg').count(),4);assert.equal(await tv.locator('mjx-assistive-mml').count(),0);assert(!(await tv.locator('.tvOptionCard').last().textContent()).includes('Chọn một phương án'));check('Algebra MCQ preserves four full-width vertical options, one rendered formula per option and separate instruction',options);await capture('MCQ_VERTICAL_MATHJAX');
 const readCases=[];for(const index of [2,4,5,6]){await go(index);await t.locator('#ansBtn').click();await settle();for(const size of [{width:1920,height:1080},{width:1366,height:768},{width:1280,height:720}]){await tv.setViewportSize(size);await settle();const s=await snapshot();readCases.push({index,...size,overflow:s.overflow,horizontal:s.horizontal});assert(!s.overflow,'Full-answer overflow index'+index);assert(!s.horizontal,'Full-answer horizontal index'+index);}}
 check('Disclosed transformation/inequality/system/error-comparison fit 12 TV viewport cases',readCases);
 await c.setOffline(true);await go(3);await t.locator('button[onclick="revealStep()"]').click();await settle();assert(await tv.locator('#answer svg').count()>0);await c.setOffline(false);check('Local MathJax continues after network disabled once assets are loaded');
 const preview=t.frames().find(f=>f.url().includes('preview=1'));await preview.waitForFunction(()=>document.getElementById('screen').dataset.algebraMathReady==='true');assert(await preview.locator('#answer svg').count()>0);assert.deepEqual(await preview.evaluate(()=>WebLiveAlgebra.getState().stepStates),await tv.evaluate(()=>WebLiveAlgebra.getState().stepStates));check('Native Teacher controls and embedded student preview share TV MathJax/disclosure');
 assert.equal(await t.evaluate(()=>JSON.stringify(lesson)),initialMemory);assert.equal(await tv.locator('#geometryTeacherControls').count(),0);assert.equal(await tv.locator('#geometryObjectHighlight').count(),0);assert.deepEqual(await tv.evaluate(()=>WebLiveAlgebra.getDiagnostics()),[]);assert.deepEqual(result.errors,[]);assert.deepEqual(result.externalRequests,[]);check('NO_TEACH_AHEAD: source memory unchanged, no generated methods, no future/answer/hint leak, no external runtime requests/errors');
 result.result='PASS';result.mathjaxVersion=await tv.evaluate(()=>MathJax.version);result.nativeWindows='UNRUN';result.realClassroomTrial='UNRUN';result.coreChangeRequired=false;fs.writeFileSync(out+'/ALGEBRA_TARGETED.json',JSON.stringify(result,null,2)+'\n');await browser.close();console.log(JSON.stringify({result:'PASS',checks:result.checks.length,captures:result.captures.length,errors:[],externalRequests:[]}));
})().catch(async e=>{result.result='FAIL';result.error={message:e.message,stack:e.stack};fs.writeFileSync(out+'/ALGEBRA_TARGETED.json',JSON.stringify(result,null,2)+'\n');await browser?.close();console.error(e);process.exitCode=1});
