const {chromium}=require('playwright'),fs=require('fs'),assert=require('assert/strict'),path=require('path');
const p=__dirname,root=process.env.P121_ROOT||p+'/working/WEB_LIVE_LESSON_LIBRARY_P12_1_WORKING_COPY',base=process.env.P121_BASE||'http://127.0.0.1:8789',out=process.env.P121_OUT||p+'/TARGETED';fs.mkdirSync(out,{recursive:true});
const finding=JSON.parse(fs.readFileSync('/workspace/p12-1-legacy-subject/FINDING_EQUIVALENT.json')),quickKey='webLiveSubjectLoaderQuickAccessPhase11',result={result:'RUNNING',checks:[],errors:[],external:[],captures:[],windowsFinding:'YES (GV_REPORTED)',windowsRetest:'UNRUN',physicalTV:'UNRUN',realClassroom:'UNRUN'};let browser;
const check=(name,evidence={})=>{result.checks.push({name,result:'PASS',evidence});console.log(name)};
const file=x=>({name:'misleading_geometry_algebra_informatics.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(x))});
(async()=>{browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});result.browser=browser.version();const c=await browser.newContext({viewport:{width:1366,height:768}});c.on('page',p=>{p.on('pageerror',e=>result.errors.push(e.message));p.on('request',r=>{if(!r.url().startsWith(base)&&!r.url().startsWith('data:'))result.external.push(r.url())})});const t=await c.newPage();await t.goto(base+'/WEB_LIVE/teacher.html');
async function subject(id){await t.evaluate(()=>showImporter());await t.locator('#lessonSubject').selectOption(id)}
async function stage(x,id){await subject(id);await t.locator('#jsonfile').setInputFiles(file(x));await t.waitForFunction(()=>!document.getElementById('subjectLoadBtn').disabled)}
async function load(){await t.locator('#subjectLoadBtn').click();await t.waitForFunction(()=>document.getElementById('importer').style.display==='none')}
const resolved=x=>t.evaluate(x=>WebLiveSubjectLoader.resolveSubject(x),x);
const snap=()=>t.evaluate(()=>({lesson:JSON.stringify(lesson),activation:lessonActivation,id:currentLessonId,index:i,answerMode,answerStep,analysisStep,showHint,zoom,focus:classroomController.focus,storage:Object.fromEntries(Object.keys(localStorage).sort().filter(k=>!['webLiveStateV042','WEB_LIVE_TTS_PRESENTATION_V1','WEB_LIVE_TTS_REGISTRY_V1'].includes(k)).map(k=>[k,localStorage.getItem(k)]))}));
await stage(finding,'informatics');const resolution=await resolved(finding);assert.deepEqual(resolution,{id:'informatics',engine:'legacy',known:true,source:'EXPLICIT_SUBJECT_METADATA'});check('LESSON_SUBJECT_SEPARATED_FROM_ENGINE');check('LEGACY_INFORMATICS_SUBJECT_RESOLUTION',{resolution});assert.equal(await t.evaluate(()=>lesson),null);check('PREVIEW_NEVER_AUTO_COMMITS');const preview=await t.locator('#subjectPreview').textContent();assert(preview.includes('Tin học 6'));assert(preview.includes('Chế độ chạyLegacy'));assert(!preview.includes('Môn của bài: Legacy'));await t.screenshot({path:out+'/FINDING_AFTER_PREVIEW.png'});result.captures.push('FINDING_AFTER_PREVIEW.png');check('PREVIEW_AND_LOADER_LABELS_SEPARATE_SUBJECT_RUNTIME');
await load();assert.equal(await t.evaluate(()=>currentLessonId),finding.id);assert.equal(await t.evaluate(()=>WebLiveProfiles.getContext().profileId),'legacy');assert.equal(await t.evaluate(()=>Object.hasOwn(lesson,'subject_engine')),false);const loaded=await t.evaluate(()=>({...lesson}));delete loaded._runtimeSourceKey;assert.deepEqual(loaded,finding);check('LEGACY_INFORMATICS_LOAD');check('LEGACY_ENGINE_PRESERVED');check('NO_ENGINE_INFERENCE',{runtime:'legacy',subjectEnginePropertyAbsent:true,contentUnchanged:true});
let q=await t.evaluate(k=>JSON.parse(localStorage.getItem(k)),quickKey);assert.equal(q.lastSubject,'informatics');assert.equal(q.recent[0].subjectEngine,'legacy');assert.equal(q.recent[0].subject,'Tin học 6');check('RECENT_STORES_ACTUAL_ENGINE_REMEMBERS_RESOLVED_SUBJECT',{lastSubject:q.lastSubject,recentEngine:q.recent[0].subjectEngine});
const pop=t.waitForEvent('popup');await t.getByRole('button',{name:'📺 MỞ TV',exact:true}).click();const tv=await pop;await tv.waitForLoadState();await t.evaluate(()=>{revealStep();zoomBy(.4);classroomController.focus={region:'answer',index:0};render();sync()});await tv.waitForFunction(()=>lastState?.answerStep===1);assert(!(await tv.locator('#screen').textContent()).includes('FUTURE_TWO'));assert(!(await tv.locator('#screen').textContent()).includes('TEACHER_PRIVATE'));check('LEGACY_NO_TEACH_AHEAD_TEACHER_NOTE_ABSENT');
await subject('informatics');assert.equal(await t.locator('#library .libraryLesson').count(),1);assert.equal(await t.locator('#library .libraryLesson').first().getAttribute('data-lesson-id'),finding.id);check('LEGACY_INFORMATICS_FILTER_VISIBILITY');for(const [field,value] of [['Grade',6],['Week',5],['Period',5]]){assert((await t.locator('#lesson'+field+' option').allTextContents()).some(x=>x.endsWith(' '+value)));await t.locator('#lesson'+field).selectOption('n:'+value);assert.equal(await t.locator('#library .libraryLesson').count(),1);check('LEGACY_INFORMATICS_'+field.toUpperCase()+'_FILTER')}
const stable=await snap(),tvStable=await tv.evaluate(()=>({id:lastState.lessonId,activation:lastState.lessonActivation,answerStep:lastState.answerStep,text:document.getElementById('screen').textContent}));for(const id of ['algebra','geometry','legacy','informatics']){await subject(id);for(const name of ['Grade','Week','Period'])assert.equal(await t.locator('#lesson'+name).inputValue(),'');assert.deepEqual(await snap(),stable)}assert.deepEqual(await tv.evaluate(()=>({id:lastState.lessonId,activation:lastState.lessonActivation,answerStep:lastState.answerStep,text:document.getElementById('screen').textContent})),tvStable);check('FILTER_AND_SUBJECT_CHANGE_CURRENT_TEACHER_TV_PRESERVED');
async function blocked(x,selected,part){const before=await snap();await subject(selected);await t.locator('#jsonfile').setInputFiles(file(x));await t.waitForFunction(part=>document.getElementById('error').textContent.includes(part),part);assert(await t.locator('#subjectLoadBtn').isDisabled());assert.deepEqual(await snap(),before);return await t.locator('#error').textContent()}
const trueMismatch=await blocked({...finding,id:'TRUE_ALGEBRA',subject:'Đại số 8',subject_engine:'algebra'},'informatics','Gói bài không khớp');assert(trueMismatch.includes('Môn của bài: Đại số'));assert(trueMismatch.includes('Chế độ chạy: Đại số'));check('TRUE_SUBJECT_MISMATCH_BLOCK',{message:trueMismatch});
let mismatchCases=0,conflictCases=0;for(const [name,id] of [['Hình học 8','geometry'],['Đại số 8','algebra'],['Tin học 6','informatics']])for(const other of ['geometry','algebra','informatics'].filter(x=>x!==id)){await blocked({...finding,id:'LEGACY_MISMATCH_'+mismatchCases,subject:name},other,'Gói bài không khớp');mismatchCases++;await blocked({...finding,id:'AMBIGUOUS_'+conflictCases,subject:name,subject_engine:other},id,'Metadata môn mâu thuẫn');conflictCases++;}check('TRUE_LEGACY_SUBJECT_MISMATCH_BLOCK',{cases:mismatchCases});check('AMBIGUOUS_METADATA_BLOCK',{cases:conflictCases});assert.deepEqual(await tv.evaluate(()=>({id:lastState.lessonId,activation:lastState.lessonActivation,answerStep:lastState.answerStep,text:document.getElementById('screen').textContent})),tvStable);check('CURRENT_LESSON_PRESERVATION',{teacher:true,tv:true,storage:true});
for(const value of ['',null,3,'unknown',{}])await blocked({...finding,id:'INVALID_ENGINE',subject_engine:value},'informatics',typeof value==='string'&&value==='unknown'?'không được hỗ trợ':'subject_engine không hợp lệ');check('INVALID_ENGINE_VALIDATION_UNWEAKENED',{cases:5});await blocked({...finding,id:'INVALID_PACKAGE',screens:[]},'informatics','screens');check('INVALID_PACKAGE_SAFETY');
const engines=['MISSING','legacy','default'];let variant=0;for(const [name,id] of [['Tin học','informatics'],['Tin học 6','informatics'],['Tin học 8','informatics'],['Hình học 8','geometry'],['Đại số 8','algebra']])for(const engine of engines){const x={...finding,id:'CROSS_'+variant++,subject:name};if(engine!=='MISSING')x.subject_engine=engine;await stage(x,id);await load();assert.equal(await t.evaluate(()=>WebLiveProfiles.getContext().profileId),'legacy');const raw=await t.evaluate(()=>lesson.subject_engine);assert.equal(raw,engine==='MISSING'?undefined:engine);q=await t.evaluate(k=>JSON.parse(localStorage.getItem(k)),quickKey);assert.equal(q.lastSubject,id);assert.equal(q.recent[0].subjectEngine,'legacy');assert.equal((await resolved(x)).id,id)}check('CROSS_SUBJECT_LEGACY_CLASSIFICATION_AND_ENGINE_PRESERVATION',{variants:variant,subjects:['geometry','algebra','informatics'],engines});
for(const id of ['geometry','algebra','informatics']){const x={...finding,id:'MODERN_'+id,subject:id,subject_engine:id};await stage(x,id);await load();assert.equal(await t.evaluate(()=>WebLiveProfiles.getContext().profileId),id);assert.equal(await t.evaluate(()=>lesson.subject_engine),id)}check('MODERN_EXPLICIT_ENGINE_ROUTING_UNCHANGED',{profiles:3});
const conservative=[{subject:'Toán 8'},{subject:'Tin học / Đại số'},{subject:'Tin học 6 — tên dài không thuộc mapping'},{subject:'Tin học 60'},{subject:'Tin học 6<script>'},{subject:'Tài liệu khác'},{}];for(const metadata of conservative){const x={...finding,...metadata};if(!Object.hasOwn(metadata,'subject'))delete x.subject;const r=await resolved(x);assert.equal(r.id,'legacy');assert.equal(r.known,false);assert.equal(r.engine,'legacy')}const deceptive={...finding,id:'NO_SUBJECT_HINTS',subject:'Tài liệu khác',title:'Hình học 8 Đại số 8 Tin học 6 T05 T05',screens:[{content:'Tin học 6 Hình học 8 Đại số 8',steps:['future']}]};await stage(deceptive,'legacy');await load();assert.equal(await t.evaluate(()=>WebLiveProfiles.getContext().profileId),'legacy');await subject('legacy');const unknown=t.locator('#library .libraryLesson').filter({hasText:'Tài liệu khác'});assert.equal(await unknown.count(),1);assert((await unknown.textContent()).includes('Môn chưa xác định'));await subject('informatics');assert.equal(await t.locator('#library .libraryLesson').filter({hasText:'Tài liệu khác'}).count(),0);check('UNKNOWN_LEGACY_BUCKET_NO_CONTENT_FILENAME_OR_TITLE_GUESS',{cases:conservative.length});
const incomplete={...finding,id:'KNOWN_SUBJECT_MISSING_GWP'};delete incomplete.grade;delete incomplete.week;delete incomplete.period;await stage(incomplete,'informatics');assert.deepEqual(await t.locator('#subjectPreview dt').allTextContents(),['Môn','Tên bài','Chế độ chạy']);await load();await subject('informatics');for(const name of ['Grade','Week','Period'])await t.locator('#lesson'+name).selectOption('missing');const missingRow=t.locator('#libraryIncomplete .libraryLesson').filter({hasText:incomplete.title});assert(await missingRow.count()>=1);assert((await missingRow.allTextContents()).some(x=>x.includes('Chưa đủ thông tin: LỚP, TUẦN, TIẾT')));assert.equal(await t.evaluate(()=>Object.hasOwn(lesson,'grade')||Object.hasOwn(lesson,'week')||Object.hasOwn(lesson,'period')||Object.hasOwn(lesson,'subject_engine')),false);check('KNOWN_LEGACY_SUBJECT_MISSING_GWP_VISIBLE_NO_INFERRED_GRADE_FROM_TIN6');
await subject('informatics');await t.locator('#zipfile').setInputFiles(root+'/RC3_PED1_TEST_PACKAGES/TIN6_W05_LIVE_RC3_PED1.zip');await t.waitForFunction(()=>!document.getElementById('subjectLoadBtn').disabled);await load();assert.equal(await t.evaluate(()=>currentLessonId),'TIN6_T05_P05_SGK_RC3_PED1');assert.equal(await t.evaluate(()=>WebLiveProfiles.getContext().profileId),'legacy');assert.equal(await t.evaluate(()=>Object.hasOwn(lesson,'subject_engine')),false);check('UNCHANGED_REAL_EXISTING_TIN6_W05_ZIP_ALLOWED_WITH_LEGACY_RUNTIME');
q=await t.evaluate(k=>JSON.parse(localStorage.getItem(k)),quickKey);assert.equal(q.lastSubject,'informatics');assert.equal(q.recent.length,5);assert.equal(new Set(q.recent.map(x=>x.id)).size,5);assert(q.recent.every(x=>!Object.hasOwn(x,'screens')&&!JSON.stringify(x).includes('data:image')));await t.reload();await t.waitForFunction(()=>currentLessonId==='TIN6_T05_P05_SGK_RC3_PED1'&&WebLiveProfiles.getContext()?.profileId==='legacy');assert.equal(await t.locator('#lessonSubject').inputValue(),'informatics');assert.equal(await t.evaluate(()=>WebLiveProfiles.getContext().profileId),'legacy');await subject('informatics');const cacheBefore=await snap();await t.locator('#recentLessons button').first().click();await t.waitForFunction(()=>!document.getElementById('subjectLoadBtn').disabled);assert.deepEqual(await snap(),cacheBefore);await load();assert.equal(await t.evaluate(()=>WebLiveProfiles.getContext().profileId),'legacy');check('RECENT_SHARED_PIPELINE_DEDUP_CAP_AND_REMEMBER_AFTER_RELOAD');
const beforeRead=await t.evaluate(k=>localStorage.getItem(k),quickKey);await t.reload();await t.waitForFunction(()=>currentLessonId==='TIN6_T05_P05_SGK_RC3_PED1'&&WebLiveProfiles.getContext()?.profileId==='legacy');assert.equal(await t.evaluate(k=>localStorage.getItem(k),quickKey),beforeRead);check('NO_QUICK_STORAGE_MIGRATION_OR_REWRITE_ON_READ');
assert.deepEqual(result.errors,[]);assert.deepEqual(result.external,[]);check('ZERO_BROWSER_ERRORS_EXTERNAL_REQUESTS');result.result='PASS';fs.writeFileSync(out+'/TARGETED_RESULTS.json',JSON.stringify(result,null,2)+'\n');await browser.close();console.log(JSON.stringify({result:'PASS',checks:result.checks.length}));})().catch(async e=>{result.result='FAIL';result.error={message:e.message,stack:e.stack};fs.writeFileSync(out+'/TARGETED_RESULTS.json',JSON.stringify(result,null,2)+'\n');await browser?.close();console.error(e);process.exitCode=1});
